### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void androidx.fragment.app.Fragment.setAnimations(int, int, int...

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#10020]
Sentry Issue: [WOOCOMMERCE-ANDROID-4XA](https://a8c.sentry.io/issues/3591766361/?referrer=github_integration)

```
NullPointerException: Attempt to invoke virtual method 'void androidx.fragment.app.Fragment.setAnimations(int, int, int, int)' on a null object reference
    at androidx.fragment.app.BackStackRecord.executePopOps(BackStackRecord.java:447)
    at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:1964)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1875)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1825)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
...
(9 additional frame(s) were not displayed)
```

**Comment by kidinov** [comment]
Many logs suggest that it may be related to the backclick on the main activity

**Comment by kidinov** [comment]
The issue appeared in 10.2 release, where we updated `implementation "androidx.fragment:fragment-ktx` to 1.5.2. My assumption that the issue is in the library itself, so lets see if this https://github.com/woocommerce/woocommerce-android/pull/9998 fixes that

**Comment by JorgeMucientes** [comment]
Closing as part of stale Sentry issue cleanup: this Sentry-linked report has had no GitHub activity for more than 6 months (cutoff: 2026-01-08). Please reopen if it is still reproducible or active in Sentry.
