### ISSUE TITLE
NullPointerException: error.message must not be null

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#10034]
Sentry Issue: [WOOCOMMERCE-ANDROID-5ZY](https://a8c.sentry.io/issues/3933337816/?referrer=github_integration)

```
NullPointerException: error.message must not be null
    at org.wordpress.android.fluxc.store.SiteStore$OnApplicationPasswordDeleteError.<init>(SiteStore.kt:802)
    at org.wordpress.android.fluxc.store.SiteStore$OnApplicationPasswordDeleted.<init>(SiteStore.kt:771)
    at org.wordpress.android.fluxc.store.SiteStore$deleteApplicationPassword$2.invokeSuspend(SiteStore.kt:2135)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
...
(4 additional frame(s) were not displayed)
```

**Comment by kidinov** [comment]
Supposed to be fixed by https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2881
