### ISSUE TITLE
Crash when trying to load feedback survey banner

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#10181]
The app crashes when trying to load the feedback survey banner when the order's `datePaid` is null.

```

FATAL EXCEPTION: main
                                                                                                    Process: com.woocommerce.android.dev, PID: 17093
                                                                                                    java.text.ParseException: Unparseable date: ""
                                                                                                    	at java.text.DateFormat.parse(DateFormat.java:393)
                                                                                                    	at com.woocommerce.android.ui.payments.feedback.ipp.GetIPPFeedbackBannerData.isIPPOrderDateAfter(GetIPPFeedbackBannerData.kt:87)
                                                                                                    	at com.woocommerce.android.ui.payments.feedback.ipp.GetIPPFeedbackBannerData.getIppOrdersforLast(GetIPPFeedbackBannerData.kt:77)
                                                                                                    	at com.woocommerce.android.ui.payments.feedback.ipp.GetIPPFeedbackBannerData.access$getIppOrdersforLast(GetIPPFeedbackBannerData.kt:25)
                                                                                                    	at com.woocommerce.android.ui.payments.feedback.ipp.GetIPPFeedbackBannerData$getIppOrdersforLast$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@42d03ea, Dispatchers.Main.immediate]

```

More context: p1700055165409509-slack-C025A8VV728

**Comment by malinajirka** [comment]
Closing since we plan to remove the survey completely.
