### ISSUE TITLE
android.os.DeadSystemException crash on Samsung devices

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1053]
Not a very helpful stacktrace:
```
Fatal Exception: java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.ActivityThread.handleSleeping(ActivityThread.java:4522)
       at android.app.ActivityThread.access$2400(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1884)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

```
Caused by android.os.DeadSystemException
       at android.app.ActivityThread.handleSleeping(ActivityThread.java:4522)
       at android.app.ActivityThread.access$2400(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1884)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Affected users:** 2 across 2 crash reports
**Fabric:** `5c88c55af8b88c2963ec6ed7`  `5c63d165f8b88c2963a658b9`
**App Version:** 1.7-rc-1 (51), 1.6
**Device:**  Samsung Galaxy Note 8 and 9 (OS version: 9.0)
**Similar issues:** #920

**Comment by anitaa1990** [comment]
Update: Seeing similar issues [here](https://stackoverflow.com/questions/49201126/runtimeexception-activitythread-handlesleeping) for Samsung devices alone.

**Comment by anitaa1990** [comment]
Since we are catching the exception and ignoring it [here](https://github.com/woocommerce/woocommerce-android/pull/945) not sure where the issue is happening.

Tried replicating the issue with Genymotion but no luck so adding `Mystery` label to it and putting it in the back burner for now.

**Comment by AmandaRiu** [comment]
An interesting thing to note is that this is only happening on Samsung devices, and only once per user. In this [SO article ](https://stackoverflow.com/questions/49201126/runtimeexception-activitythread-handlesleeping)(also posted above), they note that it also seems to only happen on devices upgrading from Android 8 to 9.

**Comment by shiki** [comment]
As of May 4, 2020: 

- 186 events
- Affected 60 users

**Comment by AmandaRiu** [comment]
As of May 18, 2020:
- 205 events
- Affected 62 users

**Comment by AmandaRiu** [comment]
Related Samsung issue: https://forum.developer.samsung.com/t/deadsystemexception/859/8

So far no answer.

**Comment by nbradbury** [comment]
As of Nov 17, 2020: 447 Events, 34 Users. 

It's happening on mainly Samsung devices, with a few others. [This Medium article](https://proandroiddev.com/oreo-notification-feature-a-critical-issue-that-could-restart-your-android-phone-ca122fa4d9cb) suggests is due to notification bug in Oreo related to setting the vibration pattern of a notification, but we don't use that feature, and we're seeing it on a variety of Android versions.

I'm tempted to simply close this issue because [the docs on DeadSystemException](https://developer.android.com/reference/android/os/DeadSystemException.html) state "The core Android system has died and is going through a runtime restart. All running apps will be promptly killed," and that doesn't seem like anything we can resolve.

**Comment by fzyzcjy** [comment]
Hi did you solve the problem? I also see this problem on my application. Though not the same app, IMHO the cause may be similar.

**Comment by nbradbury** [comment]
I've marked this issue as ignored in Sentry since it's not a problem with our code. The device is simply restarting, which kills all running processes, and if any of those processes tries to access the system at this point they'll cause this exception.

**Comment by fzyzcjy** [comment]
@nbradbury Thank you very much!

**Comment by anitaa1990** [comment]
This issue is no longer happening in Sentry so I'll close it for now. We can reopen it if it starts occurring again
