### ISSUE TITLE
Localization Error: the input currency code is not a 3-letter currency code.

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#1055]
**Describe the bug**
A user has a multisite set up and their locale is set to Italy, which reports as `it_IT`. When the UTILS tries to look up the local for a currency symbol, an error is thrown because a 3-letter code is expected.

Ref. 2016539-zen 

**Application log**

<details>

```
[May-08 12:50 WP d] API Dispatching action: WCStatsAction-FETCHED_TOP_EARNERS_STATS 
[May-08 12:50 WP d] API Dispatching action: WCStatsAction-FETCHED_VISITOR_STATS 
[May-08 12:50 WP e] API Volley error on https://public-api.wordpress.com/wpcom/v2/sites/{{site_id}}/stats/orders/?unit=year&date=2019&quantity=9&_fields=data%2Cfields&_locale=it_IT - exception: null 
[May-08 12:50 WP e] API StackTrace: com.android.volley.ClientError 
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[May-08 12:50 WP d] API Dispatching action: WCStatsAction-FETCHED_ORDER_STATS 
[May-08 12:50 DASHBOARD e] class com.woocommerce.android.ui.dashboard.DashboardPresenter - Error fetching stats: User is not allowed to access this site 
[May-08 12:50 WP e] UTILS Error finding valid currency symbol for currency code [] in locale [it_IT] - exception: The input currency code is not 3-letter alphabetic code. 
[May-08 12:50 WP e] UTILS StackTrace: java.lang.IllegalArgumentException: The input currency code is not 3-letter alphabetic code. 
at android.icu.util.Currency.getInstance(Currency.java:303) 
at java.util.Currency.getInstance(Currency.java:96) 
at org.wordpress.android.fluxc.utils.WCCurrencyUtils.getLocalizedCurrencySymbolForCode(WCCurrencyUtils.kt:45) 
at org.wordpress.android.fluxc.store.WooCommerceStore.formatCurrencyForDisplay(WooCommerceStore.kt:161) 
at com.woocommerce.android.util.CurrencyFormatter.formatCurrencyRounded(CurrencyFormatter.kt:64) 
at com.woocommerce.android.ui.dashboard.DashboardFragment$onActivityCreated$1.invoke(DashboardFragment.kt:90) 
at com.woocommerce.android.ui.dashboard.DashboardFragment$onActivityCreated$1.invoke(DashboardFragment.kt:31) 
at com.woocommerce.android.ui.dashboard.DashboardStatsView.updateView(DashboardStatsView.kt:261) 
at com.woocommerce.android.ui.dashboard.DashboardFragment.showStats(DashboardFragment.kt:148) 
at com.woocommerce.android.ui.dashboard.DashboardFragment.showStatsError(DashboardFragment.kt:154) 
at com.woocommerce.android.ui.dashboard.DashboardPresenter.onWCStatsChanged(DashboardPresenter.kt:149) 
at java.lang.reflect.Method.invoke(Native Method) 
at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507) 
at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501) 
at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:214) 
at android.app.ActivityThread.main(ActivityThread.java:6981) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

[May-08 12:50 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS 
[May-08 12:50 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDERS_COUNT 
[May-08 12:50 UTILS i] 🔵 Tracked: dashboard_unfulfilled_orders_loaded, Properties: {"has_unfulfilled_orders":true,"blog_id":<redacted>,"is_wpcom_store":false} 
[May-08 12:50 UTILS i] 🔵 Tracked: application_closed 
[May-08 12:56 UTILS i] 🔵 Tracked: application_opened 
[May-08 12:56 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"MainActivity"} 
[May-08 12:56 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"DashboardFragment"} 
[May-08 12:56 NOTIFS i] Sending FCM token to our remote services: <redacted> 
[May-08 12:56 WP d] API Dispatching action: NotificationAction-REGISTER_DEVICE 
[May-08 12:56 UTILS i] 🔵 Tracked: dashboard_pulled_to_refresh, Properties: {"blog_id":<redacted>,"is_wpcom_store":false} 
[May-08 12:56 WP d] API Dispatching action: WCStatsAction-FETCH_ORDER_STATS 
[May-08 12:56 WP d] API Dispatching action: WCStatsAction-FETCH_VISITOR_STATS 
[May-08 12:56 WP d] API Dispatching action: WCStatsAction-FETCH_TOP_EARNERS_STATS 
[May-08 12:56 WP d] API Dispatching action: WCOrderAction-FETCH_ORDERS_COUNT 
[May-08 12:56 WP d] API Dispatching action: WCOrderAction-FETCH_HAS_ORDERS 
[May-08 12:56 WP d] API Dispatching action: NotificationAction-REGISTERED_DEVICE 
[May-08 12:56 WP i] NOTIFS Server response OK. Device ID:{{device_id}} 
[May-08 12:56 WP e] API Volley error on https://public-api.wordpress.com/wpcom/v2/sites/{{site_id}}/stats/top-earners/?unit=day&date=2019-05-08&limit=3&_locale=it_IT - exception: null 
[May-08 12:56 WP e] API StackTrace: com.android.volley.ClientError 
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[May-08 12:56 WP d] API Dispatching action: WCStatsAction-FETCHED_TOP_EARNERS_STATS 
[May-08 12:56 WP d] API Dispatching action: WCStatsAction-FETCHED_VISITOR_STATS 
[May-08 12:56 WP e] API Volley error on https://public-api.wordpress.com/wpcom/v2/sites/{{site_id}}/stats/orders/?unit=year&date=2019&quantity=9&_fields=data%2Cfields&_locale=it_IT - exception: null 
[May-08 12:56 WP e] API StackTrace: com.android.volley.ClientError 
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[May-08 12:56 WP d] API Dispatching action: WCStatsAction-FETCHED_ORDER_STATS 
[May-08 12:56 DASHBOARD e] class com.woocommerce.android.ui.dashboard.DashboardPresenter - Error fetching stats: User is not allowed to access this site 
[May-08 12:56 WP e] UTILS Error finding valid currency symbol for currency code [] in locale [it_IT] - exception: The input currency code is not 3-letter alphabetic code. 
[May-08 12:56 WP e] UTILS StackTrace: java.lang.IllegalArgumentException: The input currency code is not 3-letter alphabetic code. 
at android.icu.util.Currency.getInstance(Currency.java:303) 
at java.util.Currency.getInstance(Currency.java:96) 
at org.wordpress.android.fluxc.utils.WCCurrencyUtils.getLocalizedCurrencySymbolForCode(WCCurrencyUtils.kt:45) 
at org.wordpress.android.fluxc.store.WooCommerceStore.formatCurrencyForDisplay(WooCommerceStore.kt:161) 
at com.woocommerce.android.util.CurrencyFormatter.formatCurrencyRounded(CurrencyFormatter.kt:64) 
at com.woocommerce.android.ui.dashboard.DashboardFragment$onActivityCreated$1.invoke(DashboardFragment.kt:90) 
at com.woocommerce.android.ui.dashboard.DashboardFragment$onActivityCreated$1.invoke(DashboardFragment.kt:31) 
at com.woocommerce.android.ui.dashboard.DashboardStatsView.updateView(DashboardStatsView.kt:261) 
at com.woocommerce.android.ui.dashboard.DashboardFragment.showStats(DashboardFragment.kt:148) 
at com.woocommerce.android.ui.dashboard.DashboardFragment.showStatsError(DashboardFragment.kt:154) 
at com.woocommerce.android.ui.dashboard.DashboardPresenter.onWCStatsChanged(DashboardPresenter.kt:149) 
at java.lang.reflect.Method.invoke(Native Method) 
at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507) 
at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501) 
at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:214) 
at android.app.ActivityThread.main(ActivityThread.java:6981) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

[May-08 12:56 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDERS_COUNT 
[May-08 12:56 UTILS i] 🔵 Tracked: dashboard_unfulfilled_orders_loaded, Properties: {"has_unfulfilled_orders":true,"blog_id":<redacted>,"is_wpcom_store":false} 
[May-08 12:56 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS 
[May-08 12:56 UTILS i] 🔵 Tracked: main_menu_contact_support_tapped, Properties: {"blog_id":<redacted>,"is_wpcom_store":false} 
[May-08 12:56 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"HelpActivity"} 
[May-08 12:56 UTILS i] 🔵 Tracked: support_application_log_viewed 
[May-08 12:57 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"HelpActivity"} 
[May-08 12:57 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"MainActivity"} 
[May-08 12:57 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"DashboardFragment"} 
[May-08 12:57 UTILS i] 🔵 Tracked: dashboard_pulled_to_refresh, Properties: {"blog_id":<redacted>,"is_wpcom_store":false} 
[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCH_ORDER_STATS 
[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCH_VISITOR_STATS 
[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCH_TOP_EARNERS_STATS 
[May-08 12:57 WP d] API Dispatching action: WCOrderAction-FETCH_ORDERS_COUNT 
[May-08 12:57 WP d] API Dispatching action: WCOrderAction-FETCH_HAS_ORDERS 
[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCHED_VISITOR_STATS 
[May-08 12:57 WP e] API Volley error on https://public-api.wordpress.com/wpcom/v2/sites/{{site_id}}/stats/orders/?unit=year&date=2019&quantity=9&_fields=data%2Cfields&_locale=it_IT - exception: null 
[May-08 12:57 WP e] API StackTrace: com.android.volley.ClientError 
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCHED_ORDER_STATS 
[May-08 12:57 DASHBOARD e] class com.woocommerce.android.ui.dashboard.DashboardPresenter - Error fetching stats: User is not allowed to access this site 
[May-08 12:57 WP e] UTILS Error finding valid currency symbol for currency code [] in locale [it_IT] - exception: The input currency code is not 3-letter alphabetic code. 
[May-08 12:57 WP e] UTILS StackTrace: java.lang.IllegalArgumentException: The input currency code is not 3-letter alphabetic code. 
at android.icu.util.Currency.getInstance(Currency.java:303) 
at java.util.Currency.getInstance(Currency.java:96) 
at org.wordpress.android.fluxc.utils.WCCurrencyUtils.getLocalizedCurrencySymbolForCode(WCCurrencyUtils.kt:45) 
at org.wordpress.android.fluxc.store.WooCommerceStore.formatCurrencyForDisplay(WooCommerceStore.kt:161) 
at com.woocommerce.android.util.CurrencyFormatter.formatCurrencyRounded(CurrencyFormatter.kt:64) 
at com.woocommerce.android.ui.dashboard.DashboardFragment$onActivityCreated$1.invoke(DashboardFragment.kt:90) 
at com.woocommerce.android.ui.dashboard.DashboardFragment$onActivityCreated$1.invoke(DashboardFragment.kt:31) 
at com.woocommerce.android.ui.dashboard.DashboardStatsView.updateView(DashboardStatsView.kt:261) 
at com.woocommerce.android.ui.dashboard.DashboardFragment.showStats(DashboardFragment.kt:148) 
at com.woocommerce.android.ui.dashboard.DashboardFragment.showStatsError(DashboardFragment.kt:154) 
at com.woocommerce.android.ui.dashboard.DashboardPresenter.onWCStatsChanged(DashboardPresenter.kt:149) 
at java.lang.reflect.Method.invoke(Native Method) 
at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507) 
at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501) 
at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:214) 
at android.app.ActivityThread.main(ActivityThread.java:6981) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

[May-08 12:57 WP e] API Volley error on https://public-api.wordpress.com/wpcom/v2/sites/{{site_id}}/stats/top-earners/?unit=day&date=2019-05-08&limit=3&_locale=it_IT - exception: null 
[May-08 12:57 WP e] API StackTrace: com.android.volley.ClientError 
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCHED_TOP_EARNERS_STATS 
[May-08 12:57 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS 
[May-08 12:57 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDERS_COUNT 
[May-08 12:57 UTILS i] 🔵 Tracked: dashboard_unfulfilled_orders_loaded, Properties: {"has_unfulfilled_orders":true,"blog_id":<redacted>,"is_wpcom_store":false} 
[May-08 12:57 UTILS i] 🔵 Tracked: main_tab_orders_selected, Properties: {"blog_id":161950275,"is_wpcom_store":false} 
[May-08 12:57 WP d] API Dispatching action: WCOrderAction-FETCH_ORDERS 
[May-08 12:57 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"OrderListFragment"} 
[May-08 12:57 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDERS 
[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCH_ORDER_STATS 
[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCH_VISITOR_STATS 
[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCH_TOP_EARNERS_STATS 
[May-08 12:57 WP d] API Dispatching action: WCOrderAction-FETCH_ORDERS_COUNT 
[May-08 12:57 WP d] API Dispatching action: WCOrderAction-FETCH_HAS_ORDERS 
[May-08 12:57 UTILS i] 🔵 Tracked: orders_list_loaded, Properties: {"status":"","is_loading_more":false,"blog_id":<redacted>,"is_wpcom_store":false} 
[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCHED_VISITOR_STATS 
[May-08 12:57 WP e] API Volley error on https://public-api.wordpress.com/wpcom/v2/sites/{{site_id}}/stats/top-earners/?unit=day&date=2019-05-08&limit=3&_locale=it_IT - exception: null 
[May-08 12:57 WP e] API StackTrace: com.android.volley.ClientError 
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCHED_TOP_EARNERS_STATS 
[May-08 12:57 WP e] API Volley error on https://public-api.wordpress.com/wpcom/v2/sites/{{site_id}}/stats/orders/?unit=year&date=2019&quantity=9&_fields=data%2Cfields&_locale=it_IT - exception: null 
[May-08 12:57 WP e] API StackTrace: com.android.volley.ClientError 
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) 
at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[May-08 12:57 WP d] API Dispatching action: WCStatsAction-FETCHED_ORDER_STATS 
[May-08 12:57 DASHBOARD e] class com.woocommerce.android.ui.dashboard.DashboardPresenter - Error fetching stats: User is not allowed to access this site 
[May-08 12:57 WP e] UTILS Error finding valid currency symbol for currency code [] in locale [it_IT] - exception: The input currency code is not 3-letter alphabetic code. 
[May-08 12:57 WP e] UTILS StackTrace: java.lang.IllegalArgumentException: The input currency code is not 3-letter alphabetic code. 
at android.icu.util.Currency.getInstance(Currency.java:303) 
at java.util.Currency.getInstance(Currency.java:96) 
at org.wordpress.android.fluxc.utils.WCCurrencyUtils.getLocalizedCurrencySymbolForCode(WCCurrencyUtils.kt:45) 
at org.wordpress.android.fluxc.store.WooCommerceStore.formatCurrencyForDisplay(WooCommerceStore.kt:161) 
at com.woocommerce.android.util.CurrencyFormatter.formatCurrencyRounded(CurrencyFormatter.kt:64) 
at com.woocommerce.android.ui.dashboard.DashboardFragment$onActivityCreated$1.invoke(DashboardFragment.kt:90) 
at com.woocommerce.android.ui.dashboard.DashboardFragment$onActivityCreated$1.invoke(DashboardFragment.kt:31) 
at com.woocommerce.android.ui.dashboard.DashboardStatsView.updateView(DashboardStatsView.kt:261) 
at com.woocommerce.android.ui.dashboard.DashboardFragment.showStats(DashboardFragment.kt:148) 
at com.woocommerce.android.ui.dashboard.DashboardFragment.showStatsError(DashboardFragment.kt:154) 
at com.woocommerce.android.ui.dashboard.DashboardPresenter.onWCStatsChanged(DashboardPresenter.kt:149) 
at java.lang.reflect.Method.invoke(Native Method) 
at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507) 
at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501) 
at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:214) 
at android.app.ActivityThread.main(ActivityThread.java:6981) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

[May-08 12:57 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS 
[May-08 12:57 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDERS_COUNT 
[May-08 12:57 UTILS i] 🔵 Tracked: dashboard_unfulfilled_orders_loaded, Properties: {"has_unfulfilled_orders":true,"blog_id":161950275,"is_wpcom_store":false} 
[May-08 12:57 UTILS i] 🔵 Tracked: main_menu_contact_support_tapped, Properties: {"blog_id":<redacted>,"is_wpcom_store":false} 
[May-08 12:57 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"HelpActivity"} 
[May-08 12:57 UTILS i] 🔵 Tracked: support_application_log_viewed 
[May-08 12:58 UTILS i] 🔵 Tracked: application_closed 
[May-08 13:00 UTILS i] 🔵 Tracked: application_opened 
[May-08 13:00 NOTIFS i] Sending FCM token to our remote services: <redacted> 
[May-08 13:00 WP d] API Dispatching action: NotificationAction-REGISTER_DEVICE 
[May-08 13:00 WP d] API Dispatching action: NotificationAction-REGISTERED_DEVICE 
[May-08 13:00 WP i] NOTIFS Server response OK. Device ID: 29981087 
[May-08 13:00 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"HelpActivity"} 
[May-08 13:00 UTILS i] 🔵 Tracked: support_tickets_viewed 
[May-08 13:01 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"HelpActivity"} 
[May-08 13:01 UTILS i] 🔵 Tracked: support_application_log_viewed
```

</details>

**To Reproduce**
I'm unable to reproduce it at this time and the difference is the user has multi-site set up where I do not.

1. Set your country to Italy

**Screenshots**

**Expected behavior**
The currency symbol should display for the user.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: 
- Android version: 
- WooCommerce Android version: 

**WordPress Environment**
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.

**Comment by AmandaRiu** [comment]
It looks like the real issue happened just before the crash:
```
DashboardPresenter - Error fetching stats: User is not allowed to access this site 
```
The currency code was empty because the user does not have access to the site.
