### ISSUE TITLE
IndexOutOfBoundsException: SitePickerActivity

### ISSUE THREAD

**Issue by jtreanor** [woocommerce/woocommerce-android#1081]
**Describe the bug**

A new `java.lang.IndexOutOfBoundsException` crash has surfaced in 1.8 (first seen in 1.8-rc.1). So far the occurrences are reasonably low but I will watch this carefully as the rollout is increased.

The crash occurs in `showStoreList()` which had changes in https://github.com/woocommerce/woocommerce-android/pull/1020. @nbradbury could this be related?

**Crash Log**

```
Caused by java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.woocommerce.android.ui.sitepicker.SitePickerActivity.showStoreList(SitePickerActivity.java:201)
       at com.woocommerce.android.ui.sitepicker.SitePickerActivity.onCreate(SitePickerActivity.java:116)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2742)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2872)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6543)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

5cde90cef8b88c29632854fc-fabric

**Comment by nbradbury** [comment]
It's possible it was due to [this commit](https://github.com/woocommerce/woocommerce-android/commit/10e366722f2e9b1262ccc09143d73c374a37cb19), which does have the potential to cause an `IndexOutOfBoundsException` on that line (201). Note there was the same potential with the previous code, too.

We can fix this by making sure the passed list of sites isn't empty before attempting to access the first array item.
