### ISSUE TITLE
Unable to create application com.woocommerce.android.WooCommerceDebug:

### ISSUE THREAD

**Issue by cyberespia** [woocommerce/woocommerce-android#1142]
I have the following error while trying to execute:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android, PID: 7482
    java.lang.RuntimeException: Unable to create application com.woocommerce.android.WooCommerceDebug: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[host]'
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[host]'
        at io.sentry.dsn.Dsn.validate(Dsn.java:209)
        at io.sentry.dsn.Dsn.<init>(Dsn.java:66)
        at io.sentry.dsn.Dsn.<init>(Dsn.java:41)
        at io.sentry.SentryClientFactory.resolveDsn(SentryClientFactory.java:73)
        at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:42)
        at io.sentry.Sentry.init(Sentry.java:81)
        at com.automattic.android.tracks.CrashLogging.CrashLogging.start(CrashLogging.java:43)
        at com.woocommerce.android.util.CrashUtils.initCrashLogging(CrashUtils.kt:35)
        at com.woocommerce.android.WooCommerce.onCreate(WooCommerce.kt:113)
        at com.woocommerce.android.WooCommerceDebug.onCreate(WooCommerceDebug.kt:15)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

I have followed all the instructions, some suggestions to solve this error.

**Comment by AmandaRiu** [comment]
Hi @cyberespia! Just add this line to your `gradle.properties` file and then do a clean build:
```
wc.sentry.dsn = https://00000000000000000000000000000000@sentry.io/0000000
```
