### ISSUE TITLE
[Woo POS] The app crashes during payment flow on config change

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12308]
* Start payment flow
* Init config change, e.g. change from dark to light mode
Notice crash

```
                                                                                                    java.lang.IllegalArgumentException: No destination with ID 2131364278 is on the NavController's back stack. The current destination is null
                                                                                                    	at androidx.navigation.NavController.getBackStackEntry(NavController.kt:2450)
                                                                                                    	at com.woocommerce.android.extensions.FragmentExtKt.handleResult(FragmentExt.kt:90)
                                                                                                    	at com.woocommerce.android.extensions.FragmentExtKt.handleDialogResult(FragmentExt.kt:120)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment.setupResultHandlers(SelectPaymentMethodFragment.kt:306)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment.onViewCreated(SelectPaymentMethodFragment.kt:87)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
Able to reproduce. This does Not happen when taking a custom payment by card reader in the main part of the app. Might be related to the bug where sometimes the POS mode goes back to the cart screen during checkout if you background it.
