### ISSUE TITLE
[Woo POS] ConcurrentModificationException in WooPosProductsViewModel

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12373]
Randomly I see the following crash. Unfortunately, I'm not able to reproduce it:

```
java.util.ConcurrentModificationException
                                                                                                    	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
                                                                                                    	at java.util.ArrayList$Itr.next(ArrayList.java:982)
                                                                                                    	at com.woocommerce.android.ui.woopos.home.products.WooPosProductsViewModel.toContentState(WooPosProductsViewModel.kt:231)
                                                                                                    	at com.woocommerce.android.ui.woopos.home.products.WooPosProductsViewModel.access$toContentState(WooPosProductsViewModel.kt:22)
                                                                                                    	at com.woocommerce.android.ui.woopos.home.products.WooPosProductsViewModel$toContentState$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8934)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8c8123c, Dispatchers.Main.immediate]
```
This usually happens when I run `WooPosActivity` directly from Android Studio.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
