### ISSUE TITLE
[Woo POS] Inconsistent state after activity death on the checkout state

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12418]
To reproduce:

* Enable don't keep activities
* Go to checkout
* Hide and open the app

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
I am seeing this issue occur during payment processing:

When the app is backgrounded during the payment processing, it crashes upon resumption, resulting in an `IllegalArgumentException`. 

### Steps to Reproduce:
1. Enable "Don't keep activities" in developer options.
2. Go to POS.
3. Add a product and proceed to checkout.
4. Start the payment process.
5. While the card reader is processing, background the app.
6. Resume the app.

### Expected Behavior:
The POS system should maintain the correct state and continue the payment process without crashing.

### Actual Behavior:
Upon resuming the app, it crashes with the following error log:
```
FATAL EXCEPTION: main (Ask Gemini)
Process: com.woocommerce.android.dev, PID: 10439
java.lang.IllegalArgumentException: Navigation action/destination com.woocommerce.android.dev:id/action_selectPaymentMethodFragment_to_cardReaderPaymentFlow cannot be found from the current destination Destination(com.woocommerce.android.dev:id/cardReaderPaymentDialogFragment) label=CardReaderPaymentDialogFragment
    at androidx.navigation.NavController.navigate(NavController.kt:1691)
    at androidx.navigation.NavController.navigate(NavController.kt:1609)
    at androidx.navigation.NavController.navigate(NavController.kt:2169)
    at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment$handleEvents$1.invoke(SelectPaymentMethodFragment.kt:213)
    at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment$handleEvents$1.invoke(SelectPaymentMethodFragment.kt:178)
    at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
    ...
```

**Comment by kidinov** [comment]
@backwardstruck yep, that's another one https://github.com/woocommerce/woocommerce-android/issues/12419

**Comment by backwardstruck** [comment]
> #12419

Ah, I didn't realize you already had a separate issue for it. Closing this one then.
