### ISSUE TITLE
[Woo POS] The crash if activity dies during IPP flow

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12419]
* Enabled don't keep activities
* Start payment collection flow
* Hide/open the app

```
     java.lang.IllegalArgumentException: Navigation action/destination com.woocommerce.android.dev:id/action_selectPaymentMethodFragment_to_cardReaderPaymentFlow cannot be found from the current destination Destination(com.woocommerce.android.dev:id/cardReaderConnectDialogFragment) label=CardReaderConnectDialogFragment
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1691)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1609)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:2169)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment$handleEvents$1.invoke(SelectPaymentMethodFragment.kt:213)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment$handleEvents$1.invoke(SelectPaymentMethodFragment.kt:178)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
                                                                                                    	at com.woocommerce.android.viewmodel.MultiLiveEvent$observe$1.invoke(MultiLiveEvent.kt:43)
                                                                                                    	at com.woocommerce.android.viewmodel.MultiLiveEvent$observe$1.invoke(MultiLiveEvent.kt:40)
                                                                                                    	at com.woocommerce.android.viewmodel.MultiLiveEvent$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
                                                                                                    	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                                                                                                    	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
                                                                                                    	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
                                                                                                    	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
                                                                                                    	at com.woocommerce.android.viewmodel.MultiLiveEvent.setValue(MultiLiveEvent.kt:56)
                                                                                                    	at com.woocommerce.android.viewmodel.MultiLiveEvent.setValue(MultiLiveEvent.kt:34)
                                                                                                    	at com.woocommerce.android.viewmodel.ScopedViewModel.triggerEvent(ScopedViewModel.kt:37)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel.access$triggerEvent(SelectPaymentMethodViewModel.kt:64)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel$onBtReaderClicked$1.invokeSuspend(SelectPaymentMethodViewModel.kt:308)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel.onBtReaderClicked(SelectPaymentMethodViewModel.kt:305)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel$checkStatus$1.invokeSuspend(SelectPaymentMethodViewModel.kt:126)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
