### ISSUE TITLE
Crash When Attempting to Add Package Details within Create Shipping Label Flow

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12560]
**Describe the bug**
Crash When Attempting to Add Package Details within Create Shipping Label Flow

**To Reproduce**
1. Enable Shipping labels on the app or log into a site that has shipping labels enabled
2. Follow the steps from the screen recording below and see if the app crashes with the following stacktrace:

```
FATAL EXCEPTION: main
Process: com.woocommerce.android, PID: 14806
java.lang.NumberFormatException: empty String
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:485)
	at com.woocommerce.android.model.ShippingPackageKt.toAppModel(ShippingPackage.kt:82)
	at com.woocommerce.android.ui.orders.shippinglabels.ShippingLabelRepository.getShippingPackages(ShippingLabelRepository.kt:80)
	at com.woocommerce.android.ui.orders.shippinglabels.ShippingLabelRepository$getShippingPackages$1.invokeSuspend(ShippingLabelRepository.kt:0)
```

**Screenshots**

https://github.com/user-attachments/assets/1c6c25f9-0bc7-4c49-9840-3d96825ace78

**Expected behavior**
The app should not crash when attempting to add package details

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 8
- Android version: 14
- WooCommerce Android version: 20.2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by atorresveiga** [comment]
Closing this in favor of this other issue  https://github.com/woocommerce/woocommerce-android/issues/12528
