### ISSUE TITLE
[Woo POS] App crashes when payment canceled on the payment stage

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12974]
* Open POS
* Add items 
* Start collecting payment
* When payment collection start cancel
* Notice the crash

```
FATAL EXCEPTION: main
                                                                                                    Process: com.woocommerce.android.dev, PID: 3202
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android.dev/com.woocommerce.android.ui.woopos.cardreader.WooPosCardReaderActivity}: java.lang.IllegalStateException: WooPosCardReaderMode not found in savedStateHandle
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7924)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.IllegalStateException: WooPosCardReaderMode not found in savedStateHandle
                                                                                                    	at com.woocommerce.android.ui.woopos.cardreader.WooPosCardReaderViewModel.getCardReaderMode(WooPosCardReaderViewModel.kt:33)
                                                                                                    	at com.woocommerce.android.ui.woopos.cardreader.WooPosCardReaderActivity.setupNavGraph(WooPosCardReaderActivity.kt:108)
                                                                                                    	at com.woocommerce.android.ui.woopos.cardreader.WooPosCardReaderActivity.onCreate(WooPosCardReaderActivity.kt:37)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8342)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8321)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7924) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

https://github.com/user-attachments/assets/3e93ab65-f37b-42d9-bfa7-30424832f791

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
@kidinov This has status `done` but is `open` => has it been fixed?

**Comment by kidinov** [comment]
Yep, for some reason, GH automation didn't fix the ticket 

https://github.com/woocommerce/woocommerce-android/pull/13008
