### ISSUE TITLE
IllegalStateException: orderRefreshLayout must not be null

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1344]
Sentry e0e821f8cd8348fe8006afc0dca85be9

```
ava.lang.IllegalStateException: orderRefreshLayout must not be null
    at com.woocommerce.android.ui.orders.OrderDetailFragment.refreshOrderDetail(OrderDetailFragment.kt:318)
    at com.woocommerce.android.ui.orders.OrderDetailFragment$onActivityCreated$$inlined$apply$lambda$1.onRefresh(OrderDetailFragment.kt:141)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:195)
    at androidx.swiperefreshlayout.widget.CircleImageView.onAnimationEnd(CircleImageView.java:107)
    at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:6912)
    at android.view.View.draw(View.java:20272)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
    at android.view.View.draw(View.java:20369)
    at android.view.View.updateDisplayListIfDirty(View.java:19241)
    at android.view.View.draw(View.java:20094)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4140)
    at android.view.View.updateDisplayListIfDirty(View.java:19232)
    at android.view.View.draw(View.java:20094)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
    at android.view.View.updateDisplayListIfDirty(View.java:19232)
    at android.view.View.draw(View.java:20094)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
    at android.view.View.updateDisplayListIfDirty(View.java:19232)
    at android.view.View.draw(View.java:20094)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
    at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
    at android.view.View.draw(View.java:20369)
    at android.view.View.updateDisplayListIfDirty(View.java:19241)
    at android.view.View.draw(View.java:20094)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
    at android.view.View.updateDisplayListIfDirty(View.java:19232)
    at android.view.View.draw(View.java:20094)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
    at android.view.View.updateDisplayListIfDirty(View.java:19232)
    at android.view.View.draw(View.java:20094)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
    at android.view.View.updateDisplayListIfDirty(View.java:19232)
    at android.view.View.draw(View.java:20094)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
    at android.view.View.updateDisplayListIfDirty(View.java:19232)
    at android.view.View.draw(View.java:20094)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
    at android.view.View.draw(View.java:20369)
    at com.android.internal.policy.DecorView.draw(DecorView.java:781)
    at android.view.View.updateDisplayListIfDirty(View.java:19241)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3515)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3312)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2681)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1633)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7786)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
    at android.view.Choreographer.doCallbacks(Choreographer.java:816)
    at android.view.Choreographer.doFrame(Choreographer.java:751)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6863)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by nbradbury** [comment]
Pretty sure this is because the fragment isn't added.
