### ISSUE TITLE
IllegalStateException: NotifsListFragment does not have a NavController set

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1346]
Sentry 95db08bedd174eff87efe31362583812

```
java.lang.IllegalStateException: Fragment NotifsListFragment{1d5b839 id=0x7f0a00a5 NotifsListFragment} does not have a NavController set
    at androidx.navigation.fragment.NavHostFragment.findNavController(NavHostFragment.java:119)
    at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:29)
    at com.woocommerce.android.ui.notifications.NotifsListFragment.openReviewDetail(NotifsListFragment.kt:319)
    at com.woocommerce.android.ui.main.MainActivity.showNotificationDetail(MainActivity.kt:555)
    at com.woocommerce.android.ui.main.MainActivity.initFragment(MainActivity.kt:514)
    at com.woocommerce.android.ui.main.MainActivity.onCreate(MainActivity.kt:137)
    at android.app.Activity.performCreate(Activity.java:7258)
    at android.app.Activity.performCreate(Activity.java:7249)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
    at android.app.ActivityThread.-wrap11
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:7000)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by nbradbury** [comment]
Oops, already fixed and merged... :)
