### ISSUE TITLE
ArrayIndexOutOfBoundsException in product image gallery

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1716]
[Sentry-44fccabeea7b4feeb9f4bffc93e01210](https://sentry.io/organizations/a8c/issues/1361664307/events/44fccabeea7b4feeb9f4bffc93e01210/)

```
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
    at java.util.ArrayList.get(ArrayList.java:439)
    at com.woocommerce.android.widgets.WCProductImageGalleryView$ImageGalleryAdapter.getImage(WCProductImageGalleryView.kt:112)
    at com.woocommerce.android.widgets.WCProductImageGalleryView.onImageClicked(WCProductImageGalleryView.kt:86)
    at com.woocommerce.android.widgets.WCProductImageGalleryView.access$onImageClicked(WCProductImageGalleryView.kt:27)
    at com.woocommerce.android.widgets.WCProductImageGalleryView$ImageViewHolder$1.onClick(WCProductImageGalleryView.kt:138)
    at android.view.View.performClick(View.java:6897)
    at android.view.View$PerformClick.run(View.java:26101)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
```

**Comment by nbradbury** [comment]
Closing this to generate issue from Sentry
