### ISSUE TITLE
UninitializedPropertyAccessException: lateinit property navController has not been initialized

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#1903]
Sentry Issue: [WOOCOMMERCE-ANDROID-AQ](https://sentry.io/organizations/a8c/issues/1444108049/?referrer=github_integration)

```
UninitializedPropertyAccessException: lateinit property navController has not been initialized
    at com.woocommerce.android.ui.main.MainActivity.showOrderDetail(MainActivity.kt:766)
    at com.woocommerce.android.ui.main.MainNavigationRouter$DefaultImpls.showOrderDetail$default(MainNavigationRouter.kt:7)
    at com.woocommerce.android.ui.main.MainActivity.showNotificationDetail(MainActivity.kt:716)
    at com.woocommerce.android.ui.main.MainActivity.initFragment(MainActivity.kt:682)
    at com.woocommerce.android.ui.main.MainActivity.onCreate(MainActivity.kt:156)
...
(12 additional frame(s) were not displayed)

RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property navController has not been initialized
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2891)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2969)
    at android.app.ActivityThread.-wrap11
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
    at android.os.Handler.dispatchMessage(Handler.java:108)
...
(5 additional frame(s) were not displayed)

Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property navController has not been initialized
```

**Comment by 0nko** [comment]
The exception can be reproduced by launching the app from a new order notification. It seems the changes from #1809 are the problem.
