### ISSUE TITLE
Crash:  java.lang.IllegalStateException: Multiple observers registered but only one is supported.

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2074]
When testing the products beta release, I experienced the following crash when clicking on two products from the products list, at the same time.

```
2020-03-17 11:55:52.305 8946-8946/com.woocommerce.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android, PID: 8946
    java.lang.IllegalStateException: Multiple observers registered but only one is supported.
        at com.woocommerce.android.viewmodel.LiveDataDelegate.observe(LiveDataDelegate.kt:38)
        at com.woocommerce.android.ui.products.ProductDetailFragment.setupObservers(ProductDetailFragment.kt:100)
        at com.woocommerce.android.ui.products.ProductDetailFragment.initializeViewModel(ProductDetailFragment.kt:95)
        at com.woocommerce.android.ui.products.ProductDetailFragment.onViewCreated(ProductDetailFragment.kt:91)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

#### To reproduce
- Click on the `Products` tab.
- Click on two products at the same time from the list.
- Notice app crashes with the above exception.

**Comment by shiki** [comment]
@anitaa1990 @nbradbury The fix #2076 for this was merged on 3.9 but it looks like this is [still happening for 4.0 and 4.1-rc.2](https://sentry.io/share/issue/1b9639c6a6784f5e8948491babfef7af/). 

Should we reopen this issue?

**Comment by nbradbury** [comment]
@shiki Sorry to hear that :( Yeah, we should reopen this issue.

**Comment by 0nko** [comment]
I think this can happen all over the place. I was able to reproduce it (unintentionally and unreliably) by tapping on a navigation item quickly twice. I think this is what happens:

1. Two quick taps in sequence
2. Nav component triggers a navigation action twice
3. Two instances of the same fragment are created
4. Each subscribes its ViewModel observers
4. The second fragment subscription causes the exception

So we need to create some kind of mechanism that prevents these multiple navigation actions.

**Comment by anitaa1990** [comment]
Hopefully fixed via #2401

**Comment by anitaa1990** [comment]
Happened to one user again in 4.3-rc-2. But the device is rooted so I'm not sure if this might be the cause. Re-opening the issue but marking it as On-Hold till more users get this crash again.

**Comment by nbradbury** [comment]
Re-opening this because this remains our biggest source of crashes, despite our attempts at fixing it.

<img width="1214" alt="Screen Shot 2020-09-02 at 12 18 03 PM" src="https://user-images.githubusercontent.com/3903757/92009426-7ff44600-ed16-11ea-8f88-82e8a997da82.png">

**Comment by anitaa1990** [comment]
I was able to reproduce this crash in the latest release (5.7-rc).

It looks like the `Add Product` button is visible in the Orders screen and Product detail screen. Clicking on this button from the Product detail screen is causing the Multiple observers crash. 


<img src="https://user-images.githubusercontent.com/22608780/103504916-d4ebc880-4e7e-11eb-8d96-67998e9a2c41.gif" width="300"/>

**Comment by anitaa1990** [comment]
Fixed in #3443

**Comment by anitaa1990** [comment]
This is still happening to a couple of users in v6.1 so reopening this one

**Comment by anitaa1990** [comment]
Closing this issue since it is no longer happening since v6.4 (happened to 1 user) and the current version is v7.0
