### ISSUE TITLE
Crash: when discarding the discarding a sale date change in product pricing

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2133]
I encountered the following crash when testing the product release 3.9 beta.

```
2020-03-26 19:10:55.386 9221-9221/com.woocommerce.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android, PID: 9221
    java.lang.NullPointerException: Attempt to read from field 'sun.util.calendar.BaseCalendar$Date java.util.Date.cdate' on a null object reference
        at java.util.Date.getMillisOf(Date.java:979)
        at java.util.Date.before(Date.java:938)
        at com.woocommerce.android.ui.products.ProductPricingFragment$setupObservers$1.invoke(ProductPricingFragment.kt:117)
        at com.woocommerce.android.ui.products.ProductPricingFragment$setupObservers$1.invoke(ProductPricingFragment.kt:34)
        at com.woocommerce.android.viewmodel.LiveDataDelegate$observe$1.onChanged(LiveDataDelegate.kt:43)
        at com.woocommerce.android.viewmodel.LiveDataDelegate$observe$1.onChanged(LiveDataDelegate.kt:22)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:443)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:395)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:51)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2737)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7343)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
```

This is already fixed in this [PR](PR) and has been merged into `develop` but given that this might be happening to users using the latest beta version, it would be a good idea to release a hotfix for this crash.

**Comment by anitaa1990** [comment]
Closed via #2134
