### ISSUE TITLE
Crash: IllegalStateException - cardsRecyclerView must not be null

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2425]
**Describe the bug**
App crashes when attempting to add a photo to a product. Stacktrace:

```
2020-05-13 17:24:27.086 5372-5372/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android.dev, PID: 5372
    java.lang.IllegalStateException: cardsRecyclerView must not be null
        at com.woocommerce.android.ui.products.ProductDetailFragment.onSaveInstanceState(ProductDetailFragment.kt:223)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2863)
        at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:434)
        at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:400)
        at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:143)
        at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2386)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2865)
        at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:434)
        at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:400)
        at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:143)
        at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2386)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:512)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
        at com.woocommerce.android.ui.main.MainActivity.onSaveInstanceState(MainActivity.kt:232)
        at android.app.Activity.performSaveInstanceState(Activity.java:1549)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1443)
        at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:4809)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4157)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4121)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4196)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
Possibly related to changes in this recent PR: #2383 

**To Reproduce**
1. Open a product to view the product detail
2. Click to add a product image 
3. Select from device or take a photo with camera -- app will crash.

**Video**

![ezgif com-resize (1)](https://user-images.githubusercontent.com/5810477/81876609-584b5900-9540-11ea-9590-3b6c464cf210.gif)

**Comment by AmandaRiu** [comment]
@0nko I assigned this one to you since you made recent changes to this view. Let me know if you can't work it though - I'll take it. 👍

**Comment by 0nko** [comment]
I'll take it, thanks @AmandaRiu!

**Comment by 0nko** [comment]
What version of Android are you running? I can't seem to be able to reproduce the crash...

**Comment by AmandaRiu** [comment]
@0nko I've been able to reproduce this error on the following:
- Nexus 6P API 27 (emulator)
- Pixel 3 API 28 (emulator)
- LG G5 API 28 (device)

Happens regardless of "don't keep activities" developer setting.

**Comment by AmandaRiu** [comment]
@0nko You should be able to reproduce using the current `develop` branch because I can reliably do it across multiple devices and versions so maybe update your branch? I did a little more debugging:


It's crashing in this method, so I put a debug line here:

```
override fun onSaveInstanceState(outState: Bundle) {
    println("AMANDA-TEST > ProductDetailFragment.onSaveInstanceState > $cardsRecyclerView")

    cardsRecyclerView.layoutManager?.let {
        outState.putParcelable(LIST_STATE_KEY, it.onSaveInstanceState())
    }
}
```

and tested minimizing the app and the saved instance worked fine as the recyclerView wasn't null:

```
I/System.out: AMANDA-TEST > ProductDetailFragment.onSaveInstanceState > androidx.recyclerview.widget.RecyclerView{b84c158..)
```

But after the prompt to load photos from either the device or camera, cardRecyclerView is null:

```
I/System.out: AMANDA-TEST > ProductDetailFragment.onSaveInstanceState > null
```

Some additional debugging shows that `onDestroy()` is called before `onSaveInstanceState()`... I'm not sure why. Doing a simple null check on `cardRecyclerView` doesn't work either. It will prevent the crash but the fragment still gets destroyed so you end up in a view where the DONE button isn't visible anymore so you can save and even if you could...all other changes would be lost.

**Comment by 0nko** [comment]
Weird, it really did start crashing after updating `develop`, even though I already had the changes that were causing it 🤷. Thanks for the extra info @AmandaRiu!
