### ISSUE TITLE
Navigation crash

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#2550]
The navigation crash seems to still be an issue. This happened when tapping on the Categories property in Product details.

Stack trace:
```
    Process: com.woocommerce.android, PID: 12603
    java.lang.IllegalArgumentException: navigation destination com.woocommerce.android:id/action_productDetailFragment_to_productCategoriesFragment is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:863)
        at androidx.navigation.NavController.navigate(NavController.java:804)
        at androidx.navigation.NavController.navigate(NavController.java:790)
        at androidx.navigation.NavController.navigate(NavController.java:985)
        at com.woocommerce.android.ui.products.ProductNavigator.navigate(ProductNavigator.kt:168)
        at com.woocommerce.android.ui.products.BaseProductFragment$setupObservers$1.onChanged(BaseProductFragment.kt:58)
        at com.woocommerce.android.ui.products.BaseProductFragment$setupObservers$1.onChanged(BaseProductFragment.kt:26)
        at com.woocommerce.android.viewmodel.MultiLiveEvent$observe$1.onChanged(MultiLiveEvent.kt:34)
        at com.woocommerce.android.viewmodel.MultiLiveEvent$observe$1.onChanged(MultiLiveEvent.kt:25)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.woocommerce.android.viewmodel.MultiLiveEvent.setValue(MultiLiveEvent.kt:47)
        at com.woocommerce.android.viewmodel.ScopedViewModel.triggerEvent(ScopedViewModel.kt:37)
        at com.woocommerce.android.ui.products.ProductDetailViewModel.onEditProductCardClicked(ProductDetailViewModel.kt:206)
        at com.woocommerce.android.ui.products.ProductDetailCardBuilder$categories$1.invoke(ProductDetailCardBuilder.kt:504)
        at com.woocommerce.android.ui.products.ProductDetailCardBuilder$categories$1.invoke(ProductDetailCardBuilder.kt:41)
        at com.woocommerce.android.ui.products.viewholders.ComplexPropertyViewHolder$bind$1$1.invoke(ComplexPropertyViewHolder.kt:29)
        at com.woocommerce.android.ui.products.viewholders.ComplexPropertyViewHolder$bind$1$1.invoke(ComplexPropertyViewHolder.kt:11)
        at com.woocommerce.android.ui.products.WCProductPropertyView$sam$i$android_view_View_OnClickListener$0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by anitaa1990** [comment]
Closing this issue since I cannot find this issue in Sentry anymore
