### ISSUE TITLE
IllegalArgumentException: Center point is not inside any of the rectangles!

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2682]
Sentry ISSUE: [WOOCOMMERCE-ANDROID-TJ](https://sentry.io/share/issue/b9e7abd7854a4975a47318d17d1d3ceb/)

FIRST SEEN: Aug 5, 2020 7:12:23 AM UTC
Release: 4.6
Events and Users: 1

```
java.lang.IllegalArgumentException: Center point is not inside any of the rectangles!
    at android.widget.SmartSelectSprite.startAnimation(SmartSelectSprite.java:392)
    at android.widget.SelectionActionModeHelper.startSelectionActionModeWithSmartSelectAnimation(SelectionActionModeHelper.java:323)
    at android.widget.SelectionActionModeHelper.lambda$l1f1_V5lw6noQxI_3u11qF753Iw
    at android.widget.-$$Lambda$SelectionActionModeHelper$l1f1_V5lw6noQxI_3u11qF753Iw.accept
    at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:914)
    at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:868)
    at android.os.AsyncTask.finish(AsyncTask.java:696)
    at android.os.AsyncTask.access$600(AsyncTask.java:180)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:713)
    at android.os.Handler.dispatchMessage(Handler.java:112)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by anitaa1990** [comment]
This looks to be an issue with the Aztec editor and there is an open issue [here](https://github.com/wordpress-mobile/AztecEditor-Android/issues/880) with testing steps to reproduce. Might be worth looking into.

**Comment by anitaa1990** [comment]
Happened to 3 users 1 month ago. Marking this issue as closed for now. We can reopen it again if it occurs in the future

**Comment by NStreet8579** [comment]
Hey, I'm facing the same issue. Have any of you got the solution to this issue? 
@anitaa1990
