### ISSUE TITLE
ActivityNotFoundException: Unable to find explicit activity class {com.vivo.browser/com.vivo.browser.BrowserActivity}

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2684]
[Sentry issue](https://sentry.io/share/issue/ad29575d0ff14ac0ad49f2794e0a379d/)

First seen: Aug 4, 2020 8:06:27 AM UTC
Events: 2
Users: 1
Release: 4.6

**Message**
Unable to find explicit activity class {com.vivo.browser/com.vivo.browser.BrowserActivity}; have you declared this activity in your AndroidManifest.xml?

```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.vivo.browser/com.vivo.browser.BrowserActivity}; have you declared this activity in your AndroidManifest.xml?
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1819)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1521)
    at android.app.Activity.startActivityForResult(Activity.java:4028)
    at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
    at android.app.Activity.startActivityForResult(Activity.java:3989)
    at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
    at android.app.Activity.startActivity(Activity.java:4312)
    at android.app.Activity.startActivity(Activity.java:4280)
    at android.widget.TextView.searchSelectedText(TextView.java:9669)
    at android.widget.TextView.onTextContextMenuItem(TextView.java:9354)
    at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3437)
    at com.android.internal.policy.PhoneWindow$DecorView$ActionModeCallback2Wrapper.onActionItemClicked(PhoneWindow.java:3712)
    at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:93)
    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
    at com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:126)
    at com.android.internal.widget.FloatingToolbar$FloatingToolbarMainPanel$1.onClick(FloatingToolbar.java:1093)
    at android.view.View.performClick(View.java:5212)
    at android.view.View$PerformClick.run(View.java:21214)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5619)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
```

**Comment by anitaa1990** [comment]
Interesting. Crash happened because user had the Vivo browser in their device. Since it happened to only one user 22 days ago, I'll close this issue and re-open it if it happens again.
