### ISSUE TITLE
IndexOutOfBoundsException: android.text.PackedIntVector in deleteAt 3, -1

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2685]
[Sentry issue](https://sentry.io/share/issue/409410a8bff44ffaab1425d8800156ac/)

First seen: Aug 3, 2020 11:33:21 PM UTC
Events & Users: 1
Release: 4.6

```
java.lang.IndexOutOfBoundsException: 3, -1
    at android.text.PackedIntVector.deleteAt(PackedIntVector.java:222)
    at android.text.DynamicLayout.reflow(DynamicLayout.java:317)
    at android.text.DynamicLayout.-wrap0
    at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:750)
    at android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:779)
    at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1292)
    at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:647)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
    at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
    at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:849)
    at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:618)
    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:396)
    at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```

**Comment by anitaa1990** [comment]
As of March 30th:
Events: 49
Users affected: 16
Last seen in: v6.2

**Some notes:**
- Occurred a lot in v6.0 but has reduced to 1 or 2 events per release in the last month (v6.1 & v6.2).
- It looks like this issue is related to Aztec editor and there is an open issue to track that [here](https://github.com/wordpress-mobile/AztecEditor-Android/issues/611).

**Comment by anitaa1990** [comment]
I can't seem to find this issue in Sentry anymore so will close it for now. We can reopen it if it happens again 👍
