### ISSUE TITLE
IllegalStateException: Fragment AztecEditorFragment not attached to an activity

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2687]
[Sentry issue](https://sentry.io/share/issue/446e03467e8846e0b5fc84407664b90e/)

First seen: Aug 1, 2020 1:47:41 PM UTC
Events: 1
Release: 4.6

```
java.lang.IllegalStateException: Fragment AztecEditorFragment{5347715} (2952d373-e256-4d19-90ba-9faf819bc333)} not attached to an activity.
    at androidx.fragment.app.Fragment.requireActivity(Fragment.java:833)
    at com.woocommerce.android.ui.aztec.AztecEditorFragment.onRedoEnabled(AztecEditorFragment.kt:228)
    at org.wordpress.aztec.History.updateActions(History.kt:188)
    at org.wordpress.aztec.History.doHandleHistory(History.kt:76)
    at org.wordpress.aztec.History$HistoryRunnable.run(History.kt:199)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7425)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by anitaa1990** [comment]
Closing since a more recent issue has been opened in #2732
