### ISSUE TITLE
ArrayIndexOutOfBoundsException: android.text.DynamicLayout in getBlockIndex fatal length=9; index=-3 

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2688]
[Sentry issue](https://sentry.io/share/issue/af2632b657354ceb87e1ecfcf659268e/)

First seen: Jul 28, 2020 8:52:14 PM UTC
Events and Users: 1
Release: 4.6

```
java.lang.ArrayIndexOutOfBoundsException: length=9; index=-3
    at android.text.DynamicLayout.getBlockIndex(DynamicLayout.java:648)
    at android.widget.Editor.drawHardwareAccelerated(Editor.java:1812)
    at android.widget.Editor.onDraw(Editor.java:1781)
    at android.widget.TextView.onDraw(TextView.java:6924)
    at android.view.View.draw(View.java:19337)
    at android.view.View.updateDisplayListIfDirty(View.java:18266)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at android.view.View.updateDisplayListIfDirty(View.java:18252)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at android.view.View.draw(View.java:19340)
    at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1998)
    at android.view.View.updateDisplayListIfDirty(View.java:18266)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
    at android.view.View.draw(View.java:19340)
    at android.view.View.updateDisplayListIfDirty(View.java:18266)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:235)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:223)
    at android.view.View.updateDisplayListIfDirty(View.java:18252)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:235)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:223)
    at android.view.View.updateDisplayListIfDirty(View.java:18252)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at android.view.View.updateDisplayListIfDirty(View.java:18252)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at android.view.View.updateDisplayListIfDirty(View.java:18252)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
    at android.view.View.updateDisplayListIfDirty(View.java:18252)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at android.view.View.updateDisplayListIfDirty(View.java:18252)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at android.view.View.updateDisplayListIfDirty(View.java:18252)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at android.view.View.updateDisplayListIfDirty(View.java:18252)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at android.view.View.updateDisplayListIfDirty(View.java:18252)
    at android.view.View.draw(View.java:19054)
    at android.view.ViewGroup.drawChild(ViewGroup.java:4401)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4180)
    at android.view.View.draw(View.java:19340)
    at com.android.internal.policy.DecorView.draw(DecorView.java:1015)
    at android.view.View.updateDisplayListIfDirty(View.java:18266)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3103)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2896)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2449)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1458)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6966)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
    at android.view.Choreographer.doCallbacks(Choreographer.java:798)
    at android.view.Choreographer.doFrame(Choreographer.java:730)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:972)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:192)
    at android.app.ActivityThread.main(ActivityThread.java:6754)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
```

**Comment by anitaa1990** [comment]
Crash occurred for 1 user, more than 30 days ago in release 4.6. Marking the issue as resolved for now. We can certainly re-open it at a later time, if it happens again

**Comment by nbradbury** [comment]
I'm not re-opening this, just wanted to add a comment that this crash continues to happen and it's due to a bug in Android 8. [Here's a long discussion](https://github.com/wordpress-mobile/WordPress-Android/issues/8828) of this same problem in WPAndroid.
