### ISSUE TITLE
SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2690]
Sentry Issue: [WOOCOMMERCE-ANDROID-T9](https://sentry.io/organizations/a8c/issues/1815190314/?referrer=github_integration)

First seen: Jul 29, 2020 2:48:48 AM UTC
Release: 4.6

```
SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
    at com.woocommerce.android.ui.products.ProductListRepository.getProductList(ProductListRepository.kt:138)
    at com.woocommerce.android.ui.products.ProductListViewModel$loadProducts$2.invokeSuspend(ProductListViewModel.kt:197)
...
(18 additional frame(s) were not displayed)

Row too big to fit into CursorWindow requiredPos=0, totalRows=1
```

**Comment by anitaa1990** [comment]
Possibly fixed in #2627 in version 4.7. Marking the issue as closed since I haven't seen this crash in release 4.7+
