### ISSUE TITLE
SQLiteDatabaseCorruptException: database disk image is malformed (code 11 SQLITE_CORRUPT)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2691]
Sentry Issue: [WOOCOMMERCE-ANDROID-T6](https://sentry.io/organizations/a8c/issues/1813240793/?referrer=github_integration)

First seen: Jul 29, 2020 11:42:05 AM UTC
Release: 4.6

```
SQLiteDatabaseCorruptException: database disk image is malformed (code 11 SQLITE_CORRUPT)
    at com.woocommerce.android.ui.orders.list.OrderListItemDataSource.getItemsAndFetchIfNecessary(OrderListItemDataSource.kt:50)
    at com.woocommerce.android.ui.orders.list.OrderListItemDataSource.getItemsAndFetchIfNecessary(OrderListItemDataSource.kt:38)
...
(22 additional frame(s) were not displayed)

database disk image is malformed (code 11 SQLITE_CORRUPT)
```

**Comment by anitaa1990** [comment]
Happened to 1 user in the last 3 months in version 4.6 and hasn't occurred since then. Marking this as closed. We can reopen the issue if it occurs again 👍
