### ISSUE TITLE
EventBusException: Invoking subscriber failed

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2692]
Sentry Issue: [WOOCOMMERCE-ANDROID-T7](https://sentry.io/organizations/a8c/issues/1814395168/?referrer=github_integration)

First seen: Jul 30, 2020 12:35:59 AM UTC
Release: 4.5

```
org.greenrobot.eventbus.EventBusException: Subscriber class org.wordpress.android.login.LoginWpcomService already registered to event class org.wordpress.android.fluxc.store.AccountStore$OnAccountChanged
    at org.greenrobot.eventbus.EventBus.subscribe(EventBus.java:158)
    at org.greenrobot.eventbus.EventBus.register(EventBus.java:143)
    at org.wordpress.android.fluxc.Dispatcher.register(Dispatcher.java:24)
    at org.wordpress.android.login.LoginWpcomService.onProgressStart(LoginWpcomService.java:184)
    at org.wordpress.android.util.AutoForeground.setState(AutoForeground.java:166)
    at org.wordpress.android.login.LoginWpcomService.setState(LoginWpcomService.java:226)
    at org.wordpress.android.login.LoginWpcomService.fetchAccount(LoginWpcomService.java:309)
    at org.wordpress.android.login.LoginWpcomService.onAuthenticationChanged(LoginWpcomService.java:336)
    at java.lang.reflect.Method.invoke(Method.java)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
    at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:434)
    at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:411)
    at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:384)
    at org.greenrobot.eventbus.EventBus.post(EventBus.java:265)
    at org.wordpress.android.fluxc.Dispatcher.emitChange(Dispatcher.java:41)
    at org.wordpress.android.fluxc.store.Store.emitChange(Store.java:32)
    at org.wordpress.android.fluxc.store.AccountStore$1.onResponse(AccountStore.java:1248)
    at org.wordpress.android.fluxc.store.AccountStore$1.onResponse(AccountStore.java:1241)
    at org.wordpress.android.fluxc.network.rest.wpcom.auth.Authenticator$TokenRequest.deliverResponse(Authenticator.java:126)
    at org.wordpress.android.fluxc.network.rest.wpcom.auth.Authenticator$PasswordRequest.deliverResponse(Authenticator.java:143)
    at org.wordpress.android.fluxc.network.rest.wpcom.auth.Authenticator$TokenRequest.deliverResponse(Authenticator.java:108)
    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
    at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:527)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:509)
    at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:434)
    at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:411)
    at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:384)
    at org.greenrobot.eventbus.EventBus.post(EventBus.java:265)
    at org.wordpress.android.fluxc.Dispatcher.emitChange(Dispatcher.java:41)
    at org.wordpress.android.fluxc.store.Store.emitChange(Store.java:32)
    at org.wordpress.android.fluxc.store.AccountStore$1.onResponse(AccountStore.java:1248)
    at org.wordpress.android.fluxc.store.AccountStore$1.onResponse(AccountStore.java:1241)
    at org.wordpress.android.fluxc.network.rest.wpcom.auth.Authenticator$TokenRequest.deliverResponse(Authenticator.java:126)
    at org.wordpress.android.fluxc.network.rest.wpcom.auth.Authenticator$PasswordRequest.deliverResponse(Authenticator.java:143)
    at org.wordpress.android.fluxc.network.rest.wpcom.auth.Authenticator$TokenRequest.deliverResponse(Authenticator.java:108)
    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by anitaa1990** [comment]
This crash last happened in version 5.0. The unified login changes @AmandaRiu was working on, was released in version 5.1 and this seems to have been fixed during those changes. So closing this issue.
