### ISSUE TITLE
IllegalStateException: Fragment already added ProductListFragment

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2693]
Sentry Issue: [WOOCOMMERCE-ANDROID-SK](https://sentry.io/organizations/a8c/issues/1789223551/?referrer=github_integration)

This is a strange (and old) crash that appears only recently, since the last seen was on release 3.5, so feel free to close it if you think it was solved in the latest release.

First seen: Jul 17, 2020 7:01:21 AM UTC
Release: 3.5

```
IllegalStateException: Fragment already added: ProductListFragment{2be8fec} (05f27063-a596-45f0-a7d2-06d1080b3186) id=0x7f0a00dd ProductListFragment}
    at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1625)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:405)
    at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2330)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2117)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2072)
...
(9 additional frame(s) were not displayed)

Fragment already added: ProductListFragment{2be8fec} (05f27063-a596-45f0-a7d2-06d1080b3186) id=0x7f0a00dd ProductListFragment}
```

**Comment by anitaa1990** [comment]
Closing this issue since as @pmusolino mentioned it hasn't happened since the 3.5 release.
