### ISSUE TITLE
RuntimeException android.os.AsyncTask$AsyncFutureTask in done

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2694]
Sentry Issue: [WOOCOMMERCE-ANDROID-TC](https://sentry.io/organizations/a8c/issues/1817110258/?referrer=github_integration)

First seen: Jul 31, 2020 1:45:47 PM UTC
Release: 4.6

```
RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7463)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7824)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2097)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2953)
	at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:374)

SecurityException: Permission Denial: opening provider com.google.android.apps.photos.contentprovider.impl.MediaContentProvider from ProcessRecord{eab42 21613:com.woocommerce.android/u0a227} (pid=21613, uid=10227) that is not exported from UID 10102
    at com.woocommerce.android.media.ProductImagesUtils.fetchMedia(ProductImagesUtils.kt:107)
    at com.woocommerce.android.media.ProductImagesUtils.mediaModelFromLocalUri(ProductImagesUtils.kt:36)
    at com.woocommerce.android.media.ProductImagesService.onHandleWork(ProductImagesService.kt:148)
...
(16 additional frame(s) were not displayed)

RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
...
(2 additional frame(s) were not displayed)

An error occurred while executing doInBackground()
```

**Comment by anitaa1990** [comment]
Dup of #2615
