### ISSUE TITLE
RuntimeException: android.os.TransactionTooLargeException: data parcel size 2752256 bytes

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2695]
Sentry Issue: [WOOCOMMERCE-ANDROID-Q8](https://sentry.io/organizations/a8c/issues/1715332442/?referrer=github_integration)

```
TransactionTooLargeException: data parcel size 2752256 bytes
    at android.os.BinderProxy.transactNative(BinderProxy.java)
    at android.os.BinderProxy.transact(BinderProxy.java:527)
    at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:5005)
    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
    at android.os.Handler.handleCallback(Handler.java:883)
...
(6 additional frame(s) were not displayed)

RuntimeException: android.os.TransactionTooLargeException: data parcel size 2752256 bytes
    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8016)
...
(3 additional frame(s) were not displayed)

android.os.TransactionTooLargeException: data parcel size 2752256 bytes
```

**Comment by anitaa1990** [comment]
Dup of #2594
