### ISSUE TITLE
IllegalStateException: Fragment already added: OrderListFragment

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2696]
Sentry Issue: [WOOCOMMERCE-ANDROID-EX](https://sentry.io/organizations/a8c/issues/1588111923/?referrer=github_integration)

```
IllegalStateException: Fragment already added: OrderListFragment{bf65647} (34b36c73-b282-40bb-8cbb-acb2e4afac02) id=0x7f0a00df OrderListFragment}
    at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:67)
    at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1565)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:405)
    at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
...
(10 additional frame(s) were not displayed)

Fragment already added: OrderListFragment{bf65647} (34b36c73-b282-40bb-8cbb-acb2e4afac02) id=0x7f0a00df OrderListFragment}
```

**Comment by anitaa1990** [comment]
Closing in favour of #2776
