### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void android.view.View.getDrawingRect(android.graphics.Rect)' on a null object reference

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2697]
Sentry Issue: [WOOCOMMERCE-ANDROID-SE](https://sentry.io/organizations/a8c/issues/1785444029/?referrer=github_integration)

```
NullPointerException: Attempt to invoke virtual method 'void android.view.View.getDrawingRect(android.graphics.Rect)' on a null object reference
    at androidx.core.widget.NestedScrollView.scrollToChild(NestedScrollView.java:1683)
    at androidx.core.widget.NestedScrollView.requestChildFocus(NestedScrollView.java:1792)
    at android.view.ViewGroup.requestChildFocus(ViewGroup.java:819)
    at android.view.ViewGroup.requestChildFocus(ViewGroup.java:819)
    at androidx.recyclerview.widget.RecyclerView.requestChildFocus(RecyclerView.java:2896)
...
(80 additional frame(s) were not displayed)

Attempt to invoke virtual method 'void android.view.View.getDrawingRect(android.graphics.Rect)' on a null object reference
```

**Comment by anitaa1990** [comment]
Looks like the crash happened to 2 users with rooted devices 23 days ago in version 4.6. Closing the issue till it occurs to non rooted devices.
