### ISSUE TITLE
IndexOutOfBoundsException: android.text.PackedIntVector in deleteAt fatal 14, -13

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2699]
Sentry Issue: [WOOCOMMERCE-ANDROID-PG](https://sentry.io/organizations/a8c/issues/1692282891/?referrer=github_integration)

```
IndexOutOfBoundsException: 14, -13
    at android.text.PackedIntVector.deleteAt(PackedIntVector.java:222)
    at android.text.DynamicLayout.reflow(DynamicLayout.java:317)
    at android.text.DynamicLayout.-wrap0
    at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:752)
    at android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:781)
...
(16 additional frame(s) were not displayed)

14, -13
```

**Comment by anitaa1990** [comment]
Closing this issue since it's happened 22 days ago in version 4.6. We can always reopen the issue if it happens again 👍
