### ISSUE TITLE
Crash: Add a product image by taking a picture

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#2764]
There is a crash that can be reproduced in product images with `Don't keep activities` turned on.

**To Reproduce**
1. Enable `Don't keep activities` in Developer options
2. Go to Products -> Select a product
3. Tap on "Add new image" button
4. Tap on Add photos button
5. Select the Take photo option
6. Take a picture and confirm
7. Notice the app crashed

**Stack trace**
```
com.woocommerce.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android.dev, PID: 11371
    java.lang.IllegalStateException: com.woocommerce.android.viewmodel.SavedStateWithArgs@b555e5 has null arguments
        at com.woocommerce.android.viewmodel.SavedStateWithArgs$navArgs$1.invoke(SavedStateWithArgs.kt:53)
        at com.woocommerce.android.viewmodel.SavedStateWithArgs$navArgs$1.invoke(SavedStateWithArgs.kt:20)
        at com.woocommerce.android.viewmodel.NavArgsWithDefaultLazy.getValue(NavArgsWithDefaultLazy.kt:47)
        at com.woocommerce.android.viewmodel.NavArgsWithDefaultLazy.getValue(NavArgsWithDefaultLazy.kt:35)
        at com.woocommerce.android.ui.products.ProductDetailViewModel.getNavArgs(Unknown Source:4)
        at com.woocommerce.android.ui.products.ProductDetailViewModel.start(ProductDetailViewModel.kt:163)
        at com.woocommerce.android.ui.products.ProductDetailViewModel.<init>(ProductDetailViewModel.kt:158)
        at com.woocommerce.android.ui.products.ProductDetailViewModel_AssistedFactory.create(ProductDetailViewModel_AssistedFactory.java:72)
        at com.woocommerce.android.ui.products.ProductDetailViewModel_AssistedFactory.create(ProductDetailViewModel_AssistedFactory.java:17)
        at com.woocommerce.android.viewmodel.ViewModelFactory.create(ViewModelFactory.kt:26)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.woocommerce.android.ui.products.BaseProductFragment.getViewModel(Unknown Source:2)
        at com.woocommerce.android.ui.products.BaseProductFragment.onViewCreated(BaseProductFragment.kt:50)
        at com.woocommerce.android.ui.products.ProductImagesFragment.onViewCreated(ProductImagesFragment.kt:91)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2722)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at com.woocommerce.android.ui.main.AppUpgradeActivity.onStart(AppUpgradeActivity.kt:69)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8019)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
```

**Comment by anitaa1990** [comment]
As of august 25:
Events: 60
Users affected: 5
