### ISSUE TITLE
Spike: Discover Required updates for Android P

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#287]
[Android P final beta was released today!](https://android-developers.googleblog.com/2018/07/final-preview-update-official-android-p.html) Not much should be changing so now is a good time to test the app compiled using Android P, then targeting Android P. 

This spike includes reading through API docs especially behavior changes, and working through the migration guide. All those topics and more can be found [here](https://developer.android.com/preview/). Tickets should be opened for each issue found. It would also be great if a reference to those tickets were noted in this ticket. 

### Known Issues
Issues found during a cursory check of the Woo app configured for API 28.

**ClassDefNotFoundError -- Fatal Crash**
The error:
```
 AndroidRuntime  E  FATAL EXCEPTION: Thread-4
                 E  Process: com.woocommerce.android, PID: 7140
                 E  java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/message/BasicStatusLine;
                 E      at org.wordpress.android.fluxc.network.OkHttpStack.performRequest(OkHttpStack.java:68)
                 E      at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
                 E      at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
                 E  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.message.BasicStatusLine" on path: DexPathList[[zip file "/data/app/com.woocommerce.android-c
                    gZ-xuF0VDLLJ6N5Sgy9VQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.woocommerce.android-cgZ-xuF0VDLLJ6N5Sgy9VQ==/lib/x86, /system/lib]]
                 E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
                 E      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                 E      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                 E      ... 3 more
```
[Known issue by Google](https://issuetracker.google.com/issues/79478779). Fix and reason is detailed [here](https://stackoverflow.com/questions/50461881/java-lang-noclassdeffounderrorfailed-resolution-of-lorg-apache-http-protocolve). Tested and it worked.

**BottomNavigationItemView.setShiftMode() not found**
Caused by the latest version of the build tools (28.0.1-alpha1). We can just remove this code altogether since shifting only happens when the bottom bar has more than 3 items. Currently we only have 3 so disabling shifting is unnecessary. It looks like the latest build tools will include the ability to disable shifting without reflection so this workaround wont be necessary even if we eventually need it. [[Source](https://tutel.me/c/programming/questions/40176244/how+to+disable+bottomnavigationview+shift+mode)]

**non-SDK API compliance**
NOTE: StrictMode should be added to the app to ensure any non-SDK api violations are printed in logger. [See this post for more info](https://android-developers.googleblog.com/2018/06/an-update-on-non-sdk-restrictions-in.html). I did a cursory check and found the following, but there may be more. Luckily these are currently in the _greylist_, but they will need to be addressed eventually.

```
W/ommerce.androi: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
W/ommerce.androi: Accessing hidden field Landroid/view/animation/Animation;->mListener:Landroid/view/animation/Animation$AnimationListener; (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
W/ommerce.androi: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/graphics/FontFamily;-><init>()V (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/graphics/FontFamily;->freeze()Z (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/graphics/FontFamily;->abortCreation()V (light greylist, reflection)
W/ommerce.androi: Accessing hidden method Landroid/graphics/Typeface;->createFromFamiliesWithDefault([Landroid/graphics/FontFamily;II)Landroid/graphics/Typeface; (light greylist, reflection)
```

**Comment by AmandaRiu** [comment]
We've already upgraded the app to api 28 in #761. Closing issue.
