### ISSUE TITLE
Bug: UI allows to change product status to Trashed but API fails

### ISSUE THREAD

**Issue by AliSoftware** [woocommerce/woocommerce-android#3047]
**Describe the bug**

When editing a product, the UI lists "Trashed" as a possible status to choose from; but when trying to update a product to set its status to "Trashed", we get an error toast (API error)

**To Reproduce**

1. Got to the Products list tab
2. Tap on a product to edit it
3. Tap on the 3-dots menu and select "Product Settings"
4. Tap "Status" and change the current product's status to "Trashed", then tap "Done
5. Tap "Update". The product can't be updated and we see a toast "Error updating product"

**Screenshots**

![WooAndroid53](https://user-images.githubusercontent.com/216089/96451165-774cc600-1217-11eb-8fe4-ef8f8f2a043e.gif)

**Expected behavior**

We should either allow the product to change its status to "Trashed" without having an API error, or remove the "Trashed" state from being able to be selected by the user from the Status drop down if that feature is not supposed to be allowed.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Samsung Galaxy S20 (also happens in Pixel 2 emulator)
- Android version: Android 10
- WooCommerce Android version: 5.2 (pr-3036-build-23603 from https://github.com/woocommerce/woocommerce-android/pull/3036) 

_[EDIT: just tested, still present in 5.4-rc-1]_

Note: The issue is not present in 5.1 (the "Trashed" status is not present in the dropdown on 5.1) so it's new in 5.2

**App Logs**

<details>

```
[Oct-16 16:19 WP d] API Dispatching action: WCOrderAction-FETCH_ORDER_LIST
[Oct-16 16:19 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"OrderListFragment"}
[Oct-16 16:19 WP d] API WCGatewayStore: fetchAllGateways
[Oct-16 16:19 WP d] API Dispatching action: WCOrderAction-FETCH_ORDER_STATUS_OPTIONS
[Oct-16 16:19 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDER_LIST
[Oct-16 16:19 WP d] API Dispatching action: WCOrderAction-FETCH_ORDERS_BY_IDS
[Oct-16 16:19 WP d] API Dispatching action: ListAction-FETCHED_LIST_ITEMS
[Oct-16 16:19 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDER_LIST
[Oct-16 16:19 WP d] API Dispatching action: WCOrderAction-FETCH_ORDERS_BY_IDS
[Oct-16 16:19 WP d] API Dispatching action: ListAction-FETCHED_LIST_ITEMS
[Oct-16 16:19 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDER_STATUS_OPTIONS
[Oct-16 16:19 UTILS i] 🔵 Tracked: main_tab_products_selected, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:19 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductListFragment"}
[Oct-16 16:19 WP d] API Dispatching action: WCProductAction-FETCH_PRODUCTS
[Oct-16 16:19 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCTS
[Oct-16 16:19 UTILS i] 🔵 Tracked: product_list_loaded, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:19 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductDetailFragment"}
[Oct-16 16:19 WP d] API WCTaxStore: fetchTaxClassList
[Oct-16 16:19 UTILS i] 🔵 Tracked: product_detail_view_product_description_tapped, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:19 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"AztecEditorFragment"}
[Oct-16 16:19 UTILS i] 🔵 Tracked: aztec_editor_done_button_tapped, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:19 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductDetailFragment"}
[Oct-16 16:19 UTILS i] 🔵 Tracked: product_detail_view_price_settings_tapped, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:19 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductPricingFragment"}
[Oct-16 16:20 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductItemSelectorDialog"}
[Oct-16 16:20 UTILS i] 🔵 Tracked: product_price_settings_done_button_tapped, Properties: {"has_changed_data":true,"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:20 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductDetailFragment"}
[Oct-16 16:20 WP d] API Dispatching action: WCProductAction-ADD_PRODUCT
[Oct-16 16:20 WP d] API Dispatching action: WCProductAction-ADDED_PRODUCT
[Oct-16 16:20 WP d] API WCTaxStore: fetchTaxClassList
[Oct-16 16:20 WP d] API Dispatching action: WCProductAction-FETCH_SINGLE_PRODUCT
[Oct-16 16:20 WP d] API Dispatching action: WCProductAction-FETCHED_SINGLE_PRODUCT
[Oct-16 16:20 UTILS i] 🔵 Tracked: product_detail_loaded, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:20 WP d] API Dispatching action: WCProductAction-FETCH_PRODUCT_PASSWORD
[Oct-16 16:20 WP d] API WCTaxStore: fetchTaxClassList
[Oct-16 16:20 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCT_PASSWORD
[Oct-16 16:20 UTILS i] 🔵 Tracked: back_pressed, Properties: {"context":"MainActivity"}
[Oct-16 16:20 PRODUCTS d] can't load more products
[Oct-16 16:20 UTILS i] 🔵 Tracked: product_list_pulled_to_refresh, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:20 WP d] API Dispatching action: WCProductAction-FETCH_PRODUCTS
[Oct-16 16:20 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCTS
[Oct-16 16:20 UTILS i] 🔵 Tracked: product_list_loaded, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:21 UTILS i] 🔵 Tracked: product_list_product_tapped, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:21 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductDetailFragment"}
[Oct-16 16:21 WP d] API WCTaxStore: fetchTaxClassList
[Oct-16 16:21 WP d] API Dispatching action: WCProductAction-FETCH_SINGLE_PRODUCT
[Oct-16 16:21 WP d] API Dispatching action: WCProductAction-FETCHED_SINGLE_PRODUCT
[Oct-16 16:21 UTILS i] 🔵 Tracked: product_detail_loaded, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:21 WP d] API Dispatching action: WCProductAction-FETCH_PRODUCT_PASSWORD
[Oct-16 16:21 WP d] API WCTaxStore: fetchTaxClassList
[Oct-16 16:21 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCT_PASSWORD
[Oct-16 16:21 UTILS i] 🔵 Tracked: back_pressed, Properties: {"context":"MainActivity"}
[Oct-16 16:21 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductDetailFragment"}
[Oct-16 16:21 UTILS i] 🔵 Tracked: product_settings_status_tapped, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:21 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductStatusFragment"}
[Oct-16 16:21 UTILS i] 🔵 Tracked: product_settings_done_button_tapped, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:21 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ProductDetailFragment"}
[Oct-16 16:21 UTILS i] 🔵 Tracked: back_pressed, Properties: {"context":"MainActivity"}
[Oct-16 16:21 UTILS i] 🔵 Tracked: product_detail_update_button_tapped, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:21 WP d] API Dispatching action: WCProductAction-UPDATE_PRODUCT
[Oct-16 16:21 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/183519411/rest-api/?locale=en_US - exception: null
[Oct-16 16:21 WP e] API StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Oct-16 16:21 WP d] API Dispatching action: WCProductAction-UPDATED_PRODUCT
[Oct-16 16:21 UTILS i] 🔵 Tracked: product_detail_update_error, Properties: {"error_context":"ProductDetailRepository","error_type":"INVALID_PARAM","error_description":"Invalid parameter(s): status","blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:21 UTILS i] 🔵 Tracked: product_detail_update_button_tapped, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:21 WP d] API Dispatching action: WCProductAction-UPDATE_PRODUCT
[Oct-16 16:21 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/183519411/rest-api/?locale=en_US - exception: null
[Oct-16 16:21 WP e] API StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Oct-16 16:21 WP d] API Dispatching action: WCProductAction-UPDATED_PRODUCT
[Oct-16 16:21 UTILS i] 🔵 Tracked: product_detail_update_error, Properties: {"error_context":"ProductDetailRepository","error_type":"INVALID_PARAM","error_description":"Invalid parameter(s): status","blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:22 UTILS i] 🔵 Tracked: product_detail_update_button_tapped, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:22 WP d] API Dispatching action: WCProductAction-UPDATE_PRODUCT
[Oct-16 16:22 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/183519411/rest-api/?locale=en_US - exception: null
[Oct-16 16:22 WP e] API StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Oct-16 16:22 WP d] API Dispatching action: WCProductAction-UPDATED_PRODUCT
[Oct-16 16:22 UTILS i] 🔵 Tracked: product_detail_update_error, Properties: {"error_context":"ProductDetailRepository","error_type":"INVALID_PARAM","error_description":"Invalid parameter(s): status","blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:22 UTILS i] 🔵 Tracked: back_pressed, Properties: {"context":"MainActivity"}
[Oct-16 16:22 UTILS i] 🔵 Tracked: main_tab_notifications_selected, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:22 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"ReviewListFragment"}
[Oct-16 16:22 WP d] API Dispatching action: NotificationAction-FETCH_NOTIFICATIONS
[Oct-16 16:22 WP d] API Dispatching action: WCProductAction-FETCH_PRODUCT_REVIEWS
[Oct-16 16:22 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCT_REVIEWS
[Oct-16 16:22 UTILS i] 🔵 Tracked: reviews_loaded, Properties: {"is_loading_more":false,"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:22 UTILS i] 🔵 Tracked: main_tab_dashboard_selected, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:22 WP d] API Dispatching action: WCStatsAction-FETCH_REVENUE_STATS
[Oct-16 16:22 WP d] API Dispatching action: WCStatsAction-FETCH_NEW_VISITOR_STATS
[Oct-16 16:22 WP d] API Dispatching action: WCOrderAction-FETCH_HAS_ORDERS
[Oct-16 16:22 UTILS i] 🔵 Tracked: dashboard_top_performers_loaded, Properties: {"range":"days","blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:22 WP d] API Dispatching action: WCStatsAction-FETCHED_REVENUE_STATS
[Oct-16 16:22 WP d] API Dispatching action: WCStatsAction-FETCHED_NEW_VISITOR_STATS
[Oct-16 16:22 UTILS i] 🔵 Tracked: dashboard_main_stats_loaded, Properties: {"range":"days","blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:22 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS
[Oct-16 16:22 WP d] API Dispatching action: NotificationAction-FETCHED_NOTIFICATIONS
[Oct-16 16:22 UTILS i] 🔵 Tracked: notifications_loaded, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:22 UTILS i] 🔵 Tracked: main_menu_contact_support_tapped, Properties: {"blog_id":183519411,"is_wpcom_store":true}
[Oct-16 16:22 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"HelpActivity"}
[Oct-16 16:23 UTILS i] 🔵 Tracked: support_application_log_viewed
```
</details>

**Comment by hichamboushaba** [comment]
Thanks @AliSoftware for reporting this.
Indeed the API doesn't accept the `trash` status, to trash a product we need to call the DELETE endpoint, and that is already implemented, but hidden until the products M5 release: https://github.com/woocommerce/woocommerce-android/issues/2889

I think we should just delete the option here, as it wasn't working, and it will require a lot workarounds to actually call the right endpoint instead of updating the product, and we don't want to trash products without a confirmation modal.
Do you agree @Garance91540?

**Comment by Garance91540** [comment]
> I think we should just delete the option here, as it wasn't working, and it will require a lot workarounds to actually call the right endpoint instead of updating the product, and we don't want to trash products without a confirmation modal.
Do you agree @Garance91540?

Yep, that sounds like a plan!

**Comment by Garance91540** [comment]
Could we make sure to implement a similar behavior on iOS? cc @shiki

**Comment by shiki** [comment]
Created an issue here: https://github.com/woocommerce/woocommerce-ios/issues/3288

**Comment by shiki** [comment]
@hichamboushaba Are you still planning on working on this or would you like to unassign yourself for now? 🙂

**Comment by hichamboushaba** [comment]
I totally forgot about this, let's keep it assigned to me, I'll try to have a PR this afternoon or tomorrow.
