### ISSUE TITLE
[Crash]: Order detail: app crashes when clicking on the back button after clicking on a product from the Order Detail

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3058]
When testing the app, I faced the below crash when clicking on a product from the Order detail screen and clicking the back button again.

```
2020-10-21 16:13:26.938 23693-23693/com.woocommerce.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android, PID: 23693
    kotlin.TypeCastException: null cannot be cast to non-null type com.woocommerce.android.ui.orders.details.adapter.OrderDetailProductListAdapter
        at com.woocommerce.android.ui.orders.details.views.OrderDetailProductListView.notifyProductChanged(OrderDetailProductListView.kt:70)
        at com.woocommerce.android.ui.orders.details.OrderDetailFragment.refreshProduct(OrderDetailFragment.kt:225)
        at com.woocommerce.android.ui.orders.details.OrderDetailFragment.access$refreshProduct(OrderDetailFragment.kt:62)
        at com.woocommerce.android.ui.orders.details.OrderDetailFragment$setupObservers$1.invoke(OrderDetailFragment.kt:143)
        at com.woocommerce.android.ui.orders.details.OrderDetailFragment$setupObservers$1.invoke(OrderDetailFragment.kt:62)
        at com.woocommerce.android.viewmodel.LiveDataDelegate$observe$1.onChanged(LiveDataDelegate.kt:44)
        at com.woocommerce.android.viewmodel.LiveDataDelegate$observe$1.onChanged(LiveDataDelegate.kt:22)
```

**Comment by anitaa1990** [comment]
Turns out this crash was caused by the changes in this [PR](https://github.com/woocommerce/woocommerce-android/pull/3043), which isn't actually released yet 😅
