### ISSUE TITLE
UninitializedPropertyAccessException: lateinit property order has not been initialized

### ISSUE THREAD

**Issue by AliSoftware** [woocommerce/woocommerce-android#3338]
**Sentry Url**: https://sentry.io/share/issue/df5aa7afa3434b8b9677d9f51970405f/
**User Count**: 1
**Count**: 9
**First Release**: 5.7-rc-1
**First Seen**: 2020-12-16T23:38:30Z
**Last Seen**: 2020-12-17T09:20:26Z
**24 Hours**: 8
**30 Days**: 8

```
UninitializedPropertyAccessException: lateinit property order has not been initialized
     at com.woocommerce.android.ui.orders.details.OrderDetailViewModel.hasVirtualProductsOnly(OrderDetailViewModel.kt:187)
     at com.woocommerce.android.ui.orders.details.OrderDetailFragment.showOrderDetail(OrderDetailFragment.kt:211)
     at com.woocommerce.android.ui.orders.details.OrderDetailFragment.access$showOrderDetail(OrderDetailFragment.kt:62)
     at com.woocommerce.android.ui.orders.details.OrderDetailFragment$setupObservers$1.invoke(OrderDetailFragment.kt:135)
     at com.woocommerce.android.ui.orders.details.OrderDetailFragment$setupObservers$1.invoke(OrderDetailFragment.kt:62)
     at com.woocommerce.android.viewmodel.LiveDataDelegate$observe$1.onChanged(LiveDataDelegate.kt:44)
     at com.woocommerce.android.viewmodel.LiveDataDelegate$observe$1.onChanged(LiveDataDelegate.kt:22)
     at com.woocommerce.android.ui.main.AppUpgradeActivity.onStart(AppUpgradeActivity.kt:69)
...
(41 additional frame(s) were not displayed)
```

**Comment by anitaa1990** [comment]
Fixed in #3340
