### ISSUE TITLE
Products: Crash when trying to change downloadable file download settings

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3434]
Steps to reproduce:

1. Go to Products and tap on a product that has a downloadable file (add one if needed).
1. Tap on the "Downloadable files" detail.
1. Tap the overflow menu > Download Settings.
1. Tap on the "Download limit" field.
1. Tap backspace.

**Results:** app crashes if you tap on the download limit field in downloadable file settings and press backspace. ([2m46s](https://cloudup.com/cVXVvNrOh4Z))

<img src="https://user-images.githubusercontent.com/1119271/104668624-aeefd080-5695-11eb-82f5-433cef48ff2b.png" width="270" alt="download-settings-menu-item"> <img src="https://user-images.githubusercontent.com/1119271/104668620-ae573a00-5695-11eb-9d40-f668aa6487f3.png" width="270" alt="download-settings">

<sup>Tested with WCAndroid 5.8-rc-1 on Pixel 3 Android 11 with site testingallthetime.com WordPress 5.6 WooCommerce 4.9.0 Jetpack 9.3.1 logged in as design5279.</sup>

Sentry Issue: [WOOCOMMERCE-ANDROID-17N](https://sentry.io/share/issue/a9dada8dfe074f57aaff9a2f6159341d/)

```
NumberFormatException: For input string: "9-1"
    at com.woocommerce.android.ui.products.downloads.ProductDownloadsSettingsFragment$setupListeners$2.invoke(ProductDownloadsSettingsFragment.kt:85)
    at com.woocommerce.android.ui.products.downloads.ProductDownloadsSettingsFragment$setupListeners$2.invoke(ProductDownloadsSettingsFragment.kt:19)
    at com.woocommerce.android.widgets.WCMaterialOutlinedEditTextView$setOnTextChangedListener$$inlined$doAfterTextChanged$1.afterTextChanged(TextView.kt:100)
...
(61 additional frame(s) were not displayed)

For input string: "9-1"
```

**Comment by anitaa1990** [comment]
Fixed via #3440
