### ISSUE TITLE
Shipping Labels: app crashes after continuing to edit origin address when it is empty

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-android#3479]
**To Reproduce**

Prerequisites: the store is eligible for creating shipping labels in the app - 
1. WCS should be installed and active on the store.
2. the store is in the US. 
3. the destination address for the order is in the US.

- Create an order with a physical product in core with an empty origin address
- Launch the app
- Go to the orders tab
- Tap on the order created in core
- Tap "Create shipping label" CTA
- Tap "Continue" to verify/edit the address --> the app crashes after the dialog "Address validation in progress" is shown for a few seconds

**Stacktrace**

```
D/WordPress-API: WCShippingLabelStore: verifyAddress
D/EGL_emulation: eglMakeCurrent: 0xc9875aa0: ver 3 0 (tinfo 0xc642dab0)
I/chatty: uid=10086(com.woocommerce.android) RenderThread identical 1 line
D/EGL_emulation: eglMakeCurrent: 0xc9875aa0: ver 3 0 (tinfo 0xc642dab0)
E/Volley: [9961] BasicNetwork.performRequest: Unexpected response code 500 for https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/161199960/rest-api/?locale=en_US
E/WordPress-API: Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/161199960/rest-api/?locale=en_US
    com.android.volley.ServerError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:205)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
D/WooCommerce-ORDERS: com.woocommerce.android.ui.orders.shippinglabels.creation.ShippingLabelsStateMachine$Event$AddressValidationFailed@bb035b6
D/WooCommerce-ORDERS: com.woocommerce.android.ui.orders.shippinglabels.creation.ShippingLabelsStateMachine$State$OriginAddressValidationFailure@b2882b7
I/ommerce.androi: Explicit concurrent copying GC freed 14441(883KB) AllocSpace objects, 0(0B) LOS objects, 43% free, 7MB/13MB, paused 11.150ms total 314.499ms
D/io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android, PID: 2308
    java.lang.IllegalStateException: Missing definition for state OriginAddressValidationFailure!
        at com.tinder.StateMachine.getDefinition(StateMachine.kt:54)
        at com.tinder.StateMachine.notifyOnEnter(StateMachine.kt:57)
        at com.tinder.StateMachine.transition(StateMachine.kt:30)
        at com.woocommerce.android.ui.orders.shippinglabels.creation.ShippingLabelsStateMachine.handleEvent(ShippingLabelsStateMachine.kt:328)
        at com.woocommerce.android.ui.orders.shippinglabels.creation.CreateShippingLabelViewModel.handleResult(CreateShippingLabelViewModel.kt:99)
        at com.woocommerce.android.ui.orders.shippinglabels.creation.CreateShippingLabelViewModel$handleResult$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process: Sending signal. PID: 2308 SIG: 9
```

**Screenshots**

(From Pixel 2 emulator)

creation form | after tapping "Continue"
-- | --
![Screenshot_1611655862](https://user-images.githubusercontent.com/1945542/105831723-0b41e100-6002-11eb-831b-77320843f83a.png) | ![Screenshot_1611655865](https://user-images.githubusercontent.com/1945542/105831742-0ed56800-6002-11eb-940f-e8d9bbdd026f.png)

**Expected behavior**

The app shouldn't crash, and the user can edit the origin address.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by anitaa1990** [comment]
I am no longer able to reproduce this crash. Instead getting redirected to the Edit Address screen as expected. @jaclync would like to get your confirmation before closing this issue 😄

**Comment by anitaa1990** [comment]
No longer able to reproduce this issue so closing it for now
