### ISSUE TITLE
Fatal Exception: IllegalStateException - SelectedSite.get()

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#374]
Pulled this stacktrace from Crashlytics:

```
Fatal Exception: java.lang.IllegalStateException: SelectedSite was accessed before being initialized
       at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:32)
       at com.woocommerce.android.ui.dashboard.DashboardPresenter.loadStats(DashboardPresenter.kt:64)
       at com.woocommerce.android.ui.dashboard.DashboardFragment.refreshDashboard(DashboardFragment.kt:188)
       at com.woocommerce.android.ui.dashboard.DashboardFragment.onActivityCreated(DashboardFragment.kt:91)
       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2355)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1451)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
       at android.app.Activity.performStart(Activity.java:7157)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by jkmassel** [comment]
Hi Friends,

Our nemesis is back once again.

**Source:** 5c64a639f8b88c2963bce7d9-fabric

**Comment by nbradbury** [comment]
Hmm...looks like the user is accessing settings when there's no store. I'll dig into it.
