### ISSUE TITLE
AuthFailureError: "Error fetching data", "Error fetching order", "No products yet" when logged in to a Jetpack site as a user with the Editor role

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3846]
To prepare:

<sup>TL;DR have a Jetpack site with one Administrator Jetpack-connected account and one Editor Jetpack-connected account.</sup>

* Set up a WooCommerce store hosted somewhere other than WordPress.com.
* Install, activate, and connect Jetpack using a WordPress.com account.
* Go to WP Admin > Users and create an Editor account using a different WordPress.com account email.
* Log out of both WordPress.com and WP Admin.
* Log back in to WP Admin as the user you just created.
* Go to WP Admin > Jetpack Dashboard > Account connection and click the "Link to WordPress.com" link.
* Connect to the WordPress.com with the email address of the Editor account in WP Admin.
* You should end up with something that looks similar to [this screenshot](https://user-images.githubusercontent.com/1119271/114798908-b6d21600-9d53-11eb-936b-3604021753f3.png).

To test: 

1. Log in to the WooCommerce app as a Jetpack-connected user with an Editor role.
1. Browse around in the app.

**Result:** if I log in to the WooCommerce app with a user that is Jetpack-connected but has an Editor role, the app will show "Error fetching data", "Error fetching order", and "No products yet" (even though this site does have products) and you can see many API Volley errors in the app logs mentioning "AuthFailureError". ([4m50s](https://cloudup.com/cB5VN5a6uLe))

```
[Apr-15 24:22 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/sites/191940058/stats/visits/?unit=day&date=2021-04-14&quantity=1&stat_fields=visitors&locale=en_GB - exception: null
[Apr-15 24:22 WP e] API StackTrace: com.android.volley.AuthFailureError
```

<details>
<summary>Full app logs for the timestamp matching the video</summary>

```
[Apr-15 24:22 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCTS
[Apr-15 24:22 WP d] API Dispatching action: NotificationAction-FETCH_NOTIFICATIONS
[Apr-15 24:22 WP d] API Dispatching action: WCProductAction-FETCH_PRODUCT_REVIEWS
[Apr-15 24:22 WP d] API Dispatching action: NotificationAction-FETCHED_NOTIFICATION_HASHES
[Apr-15 24:22 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCT_REVIEWS
[Apr-15 24:22 WP d] API Dispatching action: NotificationAction-FETCHED_NOTIFICATIONS
[Apr-15 24:22 WP d] API Dispatching action: WCStatsAction-FETCH_REVENUE_STATS
[Apr-15 24:22 WP d] API Dispatching action: WCStatsAction-FETCH_NEW_VISITOR_STATS
[Apr-15 24:22 WP d] API Dispatching action: WCOrderAction-FETCH_HAS_ORDERS
[Apr-15 24:22 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/sites/191940058/stats/visits/?unit=day&date=2021-04-14&quantity=1&stat_fields=visitors&locale=en_GB - exception: null
[Apr-15 24:22 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:22 WP d] API Dispatching action: WCStatsAction-FETCHED_NEW_VISITOR_STATS
[Apr-15 24:22 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching visitor stats: user cannot view stats
[Apr-15 24:22 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Forders%2F%26_method%3Dget%26per_page%3D1%26offset%3D0%26status%3Dany&json=true&locale=en_GB - exception: null
[Apr-15 24:22 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:22 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS
[Apr-15 24:22 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching whether orders exist: Sorry, you cannot list resources.
[Apr-15 24:22 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc-analytics%2Freports%2Frevenue%2Fstats%2F%26_method%3Dget%26interval%3Dhour%26after%3D2021-04-14T00%253A00%253A00%26before%3D2021-04-14T23%253A59%253A59%26per_page%3D92%26order%3Dasc&json=true&locale=en_GB - exception: null
[Apr-15 24:22 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:22 WP d] API Dispatching action: WCStatsAction-FETCHED_REVENUE_STATS
[Apr-15 24:22 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching stats: Sorry, you cannot list resources.
[Apr-15 24:30 NOTIFS i] Sending FCM token to our remote services: *** REDACTED ***
[Apr-15 24:30 WP d] API Dispatching action: NotificationAction-REGISTER_DEVICE
[Apr-15 24:30 WP d] API Dispatching action: NotificationAction-REGISTERED_DEVICE
[Apr-15 24:30 WP i] NOTIFS Server response OK. Device ID: 41284679
[Apr-15 24:31 NOTIFS i] Sending FCM token to our remote services: *** REDACTED ***
[Apr-15 24:31 WP d] API Dispatching action: NotificationAction-REGISTER_DEVICE
[Apr-15 24:31 WP d] API Dispatching action: NotificationAction-REGISTERED_DEVICE
[Apr-15 24:31 WP i] NOTIFS Server response OK. Device ID: 41284679
[Apr-15 24:31 WP d] API Dispatching action: WCOrderAction-FETCH_ORDERS_COUNT
[Apr-15 24:31 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Freports%2Forders%2Ftotals%2F%26_method%3Dget%26status%3Dprocessing&json=true&locale=en_GB - exception: null
[Apr-15 24:31 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:31 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDERS_COUNT
[Apr-15 24:31 ORDERS e] Error fetching a count of orders waiting to be fulfilled: Sorry, you cannot list resources.
[Apr-15 24:31 NOTIFS i] Sending FCM token to our remote services: *** REDACTED ***
[Apr-15 24:31 WP d] API Dispatching action: NotificationAction-REGISTER_DEVICE
[Apr-15 24:31 WP d] API Dispatching action: NotificationAction-REGISTERED_DEVICE
[Apr-15 24:31 WP i] NOTIFS Server response OK. Device ID: 41284679
[Apr-15 24:33 NOTIFS i] Sending FCM token to our remote services: *** REDACTED ***
[Apr-15 24:33 WP d] API Dispatching action: NotificationAction-REGISTER_DEVICE
[Apr-15 24:33 WP d] API Dispatching action: NotificationAction-REGISTERED_DEVICE
[Apr-15 24:33 WP i] NOTIFS Server response OK. Device ID: 41284679
[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCH_ORDERS_COUNT
[Apr-15 24:33 WP d] API Dispatching action: WCStatsAction-FETCH_REVENUE_STATS
[Apr-15 24:33 WP d] API Dispatching action: WCStatsAction-FETCH_NEW_VISITOR_STATS
[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCH_HAS_ORDERS
[Apr-15 24:33 WP d] API WCLeaderboardsStore: fetchLeaderboards
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Freports%2Forders%2Ftotals%2F%26_method%3Dget%26status%3Dprocessing&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDERS_COUNT
[Apr-15 24:33 ORDERS e] Error fetching a count of orders waiting to be fulfilled: Sorry, you cannot list resources.
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/sites/191940058/stats/visits/?unit=day&date=2021-04-14&quantity=1&stat_fields=visitors&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCStatsAction-FETCHED_NEW_VISITOR_STATS
[Apr-15 24:33 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching visitor stats: user cannot view stats
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc-analytics%2Fleaderboards%2F%26_method%3Dget%26before%3D2021-04-14T23%253A59%253A59%26after%3D2021-04-14T00%253A00%253A00%26per_page%3D3%26interval%3Dday&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Forders%2F%26_method%3Dget%26per_page%3D1%26offset%3D0%26status%3Dany&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS
[Apr-15 24:33 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching whether orders exist: Sorry, you cannot list resources.
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc-analytics%2Freports%2Frevenue%2Fstats%2F%26_method%3Dget%26interval%3Dhour%26after%3D2021-04-14T00%253A00%253A00%26before%3D2021-04-14T23%253A59%253A59%26per_page%3D81%26order%3Dasc&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCStatsAction-FETCHED_REVENUE_STATS
[Apr-15 24:33 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching stats: Sorry, you cannot list resources.
[Apr-15 24:33 WP d] API WCGatewayStore: fetchAllGateways
[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCH_ORDER_LIST
[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCH_ORDER_STATUS_OPTIONS
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Freports%2Forders%2Ftotals%2F%26_method%3Dget&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDER_STATUS_OPTIONS
[Apr-15 24:33 ORDERS e] OrderListRepository - Error fetching order status options from the api : Sorry, you cannot list resources.
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Forders%2F%26_method%3Dget%26per_page%3D60%26offset%3D0%26status%3Dany%26_fields%3Did%252Cdate_created_gmt%252Cdate_modified_gmt&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDER_LIST
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Fpayment_gateways%2F%26_method%3Dget&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: ListAction-FETCHED_LIST_ITEMS
[Apr-15 24:33 ORDERS e] AUTHORIZATION_REQUIRED: Sorry, you cannot list resources.
[Apr-15 24:34 WP d] API Dispatching action: NotificationAction-FETCH_NOTIFICATIONS
[Apr-15 24:34 WP d] API Dispatching action: WCProductAction-FETCH_PRODUCT_REVIEWS
[Apr-15 24:34 WP d] API Dispatching action: NotificationAction-FETCHED_NOTIFICATION_HASHES
[Apr-15 24:34 WP d] API Dispatching action: NotificationAction-FETCHED_NOTIFICATIONS
[Apr-15 24:34 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCT_REVIEWS
[Apr-15 24:34 WP d] API Dispatching action: WCStatsAction-FETCH_REVENUE_STATS
[Apr-15 24:34 WP d] API Dispatching action: WCStatsAction-FETCH_NEW_VISITOR_STATS
[Apr-15 24:34 WP d] API Dispatching action: WCOrderAction-FETCH_HAS_ORDERS
[Apr-15 24:34 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/sites/191940058/stats/visits/?unit=day&date=2021-04-14&quantity=1&stat_fields=visitors&locale=en_GB - exception: null
[Apr-15 24:34 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:34 WP d] API Dispatching action: WCStatsAction-FETCHED_NEW_VISITOR_STATS
[Apr-15 24:34 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching visitor stats: user cannot view stats
[Apr-15 24:34 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc-analytics%2Freports%2Frevenue%2Fstats%2F%26_method%3Dget%26interval%3Dhour%26after%3D2021-04-14T00%253A00%253A00%26before%3D2021-04-14T23%253A59%253A59%26per_page%3D81%26order%3Dasc&json=true&locale=en_GB - exception: null
[Apr-15 24:34 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:34 WP d] API Dispatching action: WCStatsAction-FETCHED_REVENUE_STATS
[Apr-15 24:34 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Forders%2F%26_method%3Dget%26per_page%3D1%26offset%3D0%26status%3Dany&json=true&locale=en_GB - exception: null
[Apr-15 24:34 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:34 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS
[Apr-15 24:34 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching stats: Sorry, you cannot list resources.
[Apr-15 24:34 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching whether orders exist: Sorry, you cannot list resources.
```
</details>

<img width="200" alt="Screen Shot 2021-04-14 at Apr 14 6 55 01 PM" src="https://user-images.githubusercontent.com/1119271/114798626-006e3100-9d53-11eb-8a37-e7e8478ebe89.png"> <img width="200" alt="Screen Shot 2021-04-14 at Apr 14 6 55 15 PM" src="https://user-images.githubusercontent.com/1119271/114798624-ff3d0400-9d52-11eb-9550-05be377a046c.png"> <img width="200" alt="Screen Shot 2021-04-14 at Apr 14 6 55 22 PM" src="https://user-images.githubusercontent.com/1119271/114798620-fe0bd700-9d52-11eb-81eb-28e4e911ba09.png">
<sup>Tested with WCAndroid 6.4-rc-2 on Pixel 3 Android 11 on favourite-saki.jurassic.ninja (WP 5.7.1-RC1 JP 9.6.1 WC 5.2.1) logged in as testuser031821 (which is a WordPress.com account username used to connect to the account with the same name on the Jetpack site and that has an Editor role there).</sup>

**Possible solutions:** 

1. Update the minimum requirements for the app to mention the account in WP Admin must be connected to Jetpack and must either be an Administrator or Shop Manager role. 
1. Add error handling for `AuthFailureError` to let the user know the role requirements and how to update that in WP Admin (make sure to note that an Administrator must make the change).

**Comment by shiki** [comment]
iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/3963
