### ISSUE TITLE
Disabling/enabling bluetooth during connection flow makes "try again" useless

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4309]
### Description
* Click connect to the reader
* During connection turn off bluetooth
* Notice "We could not connect your reader"
* Turn on Bluetooth
* Click try again
* Notice the connection doesn't succeed
* Close the dialog and start the flow again
* Notice that now you can connect

*Reproducible on Pixel 5*

### Video:

https://user-images.githubusercontent.com/4923871/123926822-f395cc80-d994-11eb-89a2-5545f2868839.mp4

### Log:
```
W/StripeTerminal: UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR: Unexpected operation in progress. Expected: class com.stripe.stripeterminal.adapter.BbposBluetoothAdapter$DiscoverReadersOperation, found: class com.stripe.stripeterminal.adapter.BbposBluetoothAdapter$DisconnectReaderOperation
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.adapter.Adapter.verifyOperationInProgress(Adapter.kt:109)
        at com.stripe.stripeterminal.adapter.BbposBluetoothAdapter.cancelDiscoverReaders$terminalsdk_release(BbposBluetoothAdapter.kt:74)
        at com.stripe.stripeterminal.adapter.MasterAdapter.cancelDiscoverReaders$terminalsdk_release(MasterAdapter.kt:33)
        at com.stripe.stripeterminal.TerminalSession.connectReader(TerminalSession.kt:111)
        at com.stripe.stripeterminal.Terminal.connectReader(Terminal.kt:180)
        at com.woocommerce.android.cardreader.internal.wrappers.TerminalWrapper.connectToReader(TerminalWrapper.kt:45)
        at com.woocommerce.android.cardreader.internal.connection.ConnectionManager.connectToReader(ConnectionManager.kt:54)
        at com.woocommerce.android.cardreader.internal.CardReaderManagerImpl.connectToReader(CardReaderManagerImpl.kt:81)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel$onConnectToReaderClicked$2.invokeSuspend(CardReaderConnectViewModel.kt:242)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:349)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel.onConnectToReaderClicked(CardReaderConnectViewModel.kt:241)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel.access$onConnectToReaderClicked(CardReaderConnectViewModel.kt:56)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel$onConnectToReaderClicked$2$1.invoke(CardReaderConnectViewModel.kt:249)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel$onConnectToReaderClicked$2$1.invoke(CardReaderConnectViewModel.kt:56)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectFragment$observeState$1$1.onClick(CardReaderConnectFragment.kt:101)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by malinajirka** [comment]
Note: This is reproducible only on some devices. Works as expected on Samsung Z Flip with Android 11.
