### ISSUE TITLE
WCStatsStore IllegalStateException - Missing field from stats endpoint

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#447]
Fabric reported the following exception:
```
Non-fatal Exception: java.lang.IllegalStateException: Missing field from stats endpoint
       at org.wordpress.android.fluxc.store.WCStatsStore.reportMissingFieldError(WCStatsStore.kt:331)
       at org.wordpress.android.fluxc.store.WCStatsStore.getStatsForField(WCStatsStore.kt:319)
       at org.wordpress.android.fluxc.store.WCStatsStore.getOrderStats(WCStatsStore.kt:198)
       at com.woocommerce.android.ui.dashboard.DashboardPresenter.onWCStatsChanged(DashboardPresenter.kt:144)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
Looking at the code, we append the raw fields returned by the api:
```
["period","orders","products","coupons","coupon_discount","total_sales","total_tax","total_shipping","total_shipping_tax","total_refund","total_tax_refund","total_shipping_refund","total_shipping_tax_refund","currency","gross_sales","net_sales","avg_order_value","avg_products_per_order"]
```
but we do not report what field we were looking for that caused the exception. Add the field to the message for future troubleshooting and review.

**Comment by nbradbury** [comment]
Looking at Fabric crash reports, the missing field in every case appears to be "orders." Stack trace shows that is happening when calling [getOrderStats()](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/fca18a13a5e2bc81edd10f313a4c4eaa3c004408/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCStatsStore.kt#L197), which retrieves only the stats for the orders field.

```

FluxC: Missing field from stats endpoint: Missing field: orders, returned fields: ["period","orders","products","coupons","coupon_discount","total_sales","total_tax","total_shipping","total_shipping_tax","total_refund","total_tax_refund","total_shipping_refund","total_shipping_tax_refund","currency","gross_sales","net_sales","avg_order_value","avg_products_per_order"]
--

Non-fatal Exception: java.lang.IllegalStateException: Missing field from stats endpoint
       at org.wordpress.android.fluxc.store.WCStatsStore.reportMissingFieldError(WCStatsStore.kt:332)
       at org.wordpress.android.fluxc.store.WCStatsStore.getStatsForField(WCStatsStore.kt:319)
       at org.wordpress.android.fluxc.store.WCStatsStore.getOrderStats(WCStatsStore.kt:198)
       at com.woocommerce.android.ui.dashboard.DashboardPresenter.onWCStatsChanged(DashboardPresenter.kt:178)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:171)
       at android.app.ActivityThread.main(ActivityThread.java:6699)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

**Comment by AmandaRiu** [comment]
Issue has not happened in a while. Closing ticket.
