### ISSUE TITLE
Product variations: handle null image response from API

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#4746]
While testing this [PR](https://github.com/woocommerce/woocommerce-android/pull/4720), I found that I was not able to see any of the images for a variation of a product. I kept getting the following error in the logs:
```
2021-09-08 10:57:38.528 15432-19665/com.woocommerce.android.dev E/WordPress-API: Not a JSON Object: null
    java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at org.wordpress.android.fluxc.model.WCProductVariationModel.getImageModel(WCProductVariationModel.kt:120)
        at com.woocommerce.android.model.ProductVariationKt.toAppModel(ProductVariation.kt:191)
        at com.woocommerce.android.ui.products.variations.VariationRepository.handleVariationCreateResult(VariationRepository.kt:113)
        at com.woocommerce.android.ui.products.variations.VariationRepository.access$handleVariationCreateResult(VariationRepository.kt:31)
        at com.woocommerce.android.ui.products.variations.VariationRepository$createEmptyVariation$2.invokeSuspend(VariationRepository.kt:94)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

#### To reproduce
- Generate a new variable product.
- Generate new attributes and generate variations from those attributes.
- Notice that you are redirected to the variation list screen.
- And in the logs you will find this error stacktrace. 

This seems to be happening in the `image` field in the API response because it is `null` but the app is expected an empty array or object. cc @ThomazFB and @wzieba, I'm not sure how important this issue is but would one of you be able to take a look please 🙇‍♀️

**Comment by malinajirka** [comment]
Automated reproduction attempt/comment on June 15, 2026: I reproduced that this is still relevant on the staging site. I created variable product #6120, Codex Null Image Variation 4746, with two no-image variations (#6121 Small and #6122 Large). In WooCommerce Android on emulator-5558, the Variations screen rendered both variations, but logcat still showed the original error twice: WordPress-API: Not a JSON Object: null, java.lang.IllegalStateException at WCProductVariationModel.getImageModel and VariationRepository.getProductVariationList. I migrated this to Linear: https://linear.app/a8c/issue/WOOMOB-3246/android-variation-list-still-logs-error-when-variation-image-payload. Closing this GitHub issue in favor of Linear.
