### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.SiteModel.getId()' on a n...

### ISSUE THREAD

**Issue by AliSoftware** [woocommerce/woocommerce-android#4807]
**Sentry Url**: https://sentry.io/share/issue/af5a95883b1a47628b71df8e812b8cf4/
**User Count**: 250
**Count**: 1240
**First Release**: 17.8-rc-1
**First Seen**: 2021-07-14T18:24:13.241000Z
**Last Seen**: 2021-09-17T11:36:44Z
**24 Hours**: 24
**30 Days**: 793

```
NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.SiteModel.getId()' on a null object reference
     at org.wordpress.android.ui.plugins.PluginDetailActivity.shouldHandleFluxCSitePluginEvent(PluginDetailActivity.java:1161)
     at org.wordpress.android.ui.plugins.PluginDetailActivity.onSitePluginConfigured(PluginDetailActivity.java:966)
...
(2 additional frame(s) were not displayed)
```

**Comment by AliSoftware** [comment]
Sorry, that was meant for WPAndroid, not WCAndroid. Closing.
