### ISSUE TITLE
SelectedSite crash in OrderListViewModel

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4842]
In #4114 we tracked a `selectedSite.get()` crash during login, but we're still seeing similar crashes in `OrderDetailViewModel.init()`. From [the Sentry report](https://sentry.io/organizations/a8c/issues/2155569010/events/e191132251db4a4e8e56dab85d3d3430/):

```
java.lang.IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId 2.
Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
    at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:36)
    at com.woocommerce.android.ui.orders.list.OrderListViewModel$1.invokeSuspend(OrderListViewModel.kt:134)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
```

**Comment by nbradbury** [comment]
The crash is happening [here](https://github.com/woocommerce/woocommerce-android/blob/82d28c357809e7289a58f649b0e7a098ca1c8b3c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt#L134) in `OrderListViewModel.init().` 

Sentry's breadcrumbs are inconsistent, but most of them show this happening after `MainActivity` is created, and some of them show that `SitePickerActivity` was returned from. That sounds like it's happening after login, but a few breadcrumbs show the user just accessed settings. So it sounds like the user switched sites, especially since the order list fragment wouldn't have been added yet if the user came from login.

**Update:** I meant to add that in the majority of cases the selected site ID is valid - it's not `-1`.

**Comment by nbradbury** [comment]
I can confirm that if you switch to the order list, switch back to My Store, tap settings and switch stores, when you exit settings the first call to `selectedSite.get()` comes from `OrderListViewModel`.

As a test I nullified the selected site and set an invalid selected site ID when leaving the site picker, and when I returned to the main activity the app crashed in `OrderListViewModel.init()`. 

The mystery is how the user could return from the site picker with a valid (not `-1`) selected site ID, but when they leave settings the site isn't retrievable from the site store.

**Comment by nbradbury** [comment]
Based on our Slack discussions, here's what we think is happening:

- Site picker is shown
- Request to fetch sites is sent
- Fetch completes and chosen site no longer exists
- Use hits the back button to return to settings and then returns to the main activity
- The order list is re-attached but the site is no longer in the db
- Boom!

We can resolve this crash by using `selectedSite.getIfExists()` instead of `selectedSite.get()`, but then we’re left with three problems:

1. There’s no longer a selected site so the user needs to choose another one
2. The above won’t work if it was their only site, so wee need to tell the user and probably (?) log them out
3. Ideally we don’t want to fix this in the order list but instead in the site picker or settings screens, otherwise this could happen elsewhere down the road
