### ISSUE TITLE
Fix crash when login in the app for the first time

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#5790]
When login in for the first time the app crashes when trying to display more menu badge

```

     Caused by: java.lang.IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId -1.
    Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
        at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:48)
        at com.woocommerce.android.ui.main.MainActivityViewModel.removeReviewNotifications(MainActivityViewModel.kt:40)
        at com.woocommerce.android.ui.main.MainActivity.showMoreMenuBadge(MainActivity.kt:659)
        at com.woocommerce.android.ui.main.MainPresenter.takeView(MainPresenter.kt:70)
        at com.woocommerce.android.ui.main.MainPresenter.takeView(MainPresenter.kt:31)
        at com.woocommerce.android.ui.main.MainActivity.onCreate(MainActivity.kt:206)
```

**Comment by anitaa1990** [comment]
Closed via #5791
