### ISSUE TITLE
Crash during logout

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#5946]
**Describe the bug**
When I logout the app crashes with the following exception:
```
FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.woocommerce.android.dev, PID: 12315
    java.lang.IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId -1.
    Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
        at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:48)
        at com.woocommerce.android.push.UnseenReviewsCountHandler$special$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:220)
        at com.woocommerce.android.push.UnseenReviewsCountHandler$special$$inlined$flatMapLatest$1.invoke(Unknown Source:13)
        at com.woocommerce.android.push.UnseenReviewsCountHandler$special$$inlined$flatMapLatest$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1.emit(Collect.kt:140)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**To Reproduce**
1. Go to More sectoin
2. Click on App settings
3. Click on "Logout"
4. See crash

**Expected behavior**
The app should not crash and should redirect the user to the login screen

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shiki** [comment]
This also happened to me today. I see there's a PR for this but just in case it still helps, here's the stacktrace:

```
2022-03-01 10:03:27.186 9302-9444/com.woocommerce.android.prealpha E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.woocommerce.android.prealpha, PID: 9302
    java.lang.IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId -1.
    Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
        at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:48)
        at com.woocommerce.android.push.UnseenReviewsCountHandler$special$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:220)
        at com.woocommerce.android.push.UnseenReviewsCountHandler$special$$inlined$flatMapLatest$1.invoke(Unknown Source:13)
        at com.woocommerce.android.push.UnseenReviewsCountHandler$special$$inlined$flatMapLatest$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1.emit(Collect.kt:140)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
