### ISSUE TITLE
Crash when notification comes

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#7161]
```
IllegalStateException
SelectedSite.get() was accessed before being initialized - siteId -1.
Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().

com.woocommerce.android.tools.SelectedSite in get at line 48
com.woocommerce.android.ui.main.MainActivityViewModel in handleIncomingNotification at line 58
com.woocommerce.android.ui.main.MainActivity in initFragment at line 680
com.woocommerce.android.ui.main.MainActivity in onCreate at line 269
android.app.Activity in performCreate at line 7458
android.app.Activity in performCreate at line 7448
android.app.Instrumentation in callActivityOnCreate at line 1286
android.app.ActivityThread in performLaunchActivity at line 3409
android.app.ActivityThread in handleLaunchActivity at line 3614
android.app.servertransaction.LaunchActivityItem in execute at line 86
android.app.servertransaction.TransactionExecutor in executeCallbacks at line 108
android.app.servertransaction.TransactionExecutor in execute at line 68
android.app.ActivityThread$H in handleMessage at line 2199
android.os.Handler in dispatchMessage at line 112
android.os.Looper in loop at line 216
android.app.ActivityThread in main at line 7625
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 524
com.android.internal.os.ZygoteInit in main at line 987
```

**Comment by kidinov** [comment]
Without any knowledge how notificaions work in the app, my best guess is that notification comes on "Site picker" screen, we still don't have selected site local id stored in the preferences

To verify that, I sent push
```
adb shell am broadcast -a com.google.android.c2dm.intent.RECEIVE -n com.woocommerce.android.dev/com.google.firebase.iid.FirebaseInstanceIdReceiver com.woocommerce.android.dev/com.google.firebase.iid.FirebaseInstanceIdReceiver --es "user" "193905569"
```

In order to make it work:

```
        <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="@null"
            tools:replace="android:permission">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="com.picpay.debug" />
            </intent-filter>
        </receiver>
```
has to be added to the manifest

and added to the NotificationMessageHandler::onNewMessageReceived this line:

 ```
wooLogWrapper.e(NOTIFS, "selectedSite - ${selectedSite.get()}")
```

It crashes with the same error:
```
    java.lang.IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId -1.
    Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
        at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:48)
        at com.woocommerce.android.push.NotificationMessageHandler.onNewMessageReceived(NotificationMessageHandler.kt:110)
```

![image](https://user-images.githubusercontent.com/4923871/184094307-114aa059-ad43-4783-bdc9-e9de9fdeb6ff.png)
