### ISSUE TITLE
IllegalStateException: Login epilogue instance state

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#717]
```
Caused by java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
       at android.support.v4.app.DialogFragment.show(DialogFragment.java:160)
       at com.woocommerce.android.ui.login.LoginEpilogueActivity.siteVerificationFailed(LoginEpilogueActivity.kt:165)
       at com.woocommerce.android.ui.login.LoginEpiloguePresenter.onApiVersionFetched(LoginEpiloguePresenter.kt:97)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

[Fabric](https://fabric.io/automattic/android/apps/com.woocommerce.android/issues/5c475039f8b88c296326fede?time=last-ninety-days)

**Comment by nbradbury** [comment]
To repro, step through the login process and minimize the app during the site verification process. Noter that "Don't keep activities" should **not** be enabled.
