### ISSUE TITLE
RuntimeException: AddOrderNote

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#720]
```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.orders.AddOrderNoteActivity}: 
java.lang.IllegalStateException: intent.getStringExtra(FIELD_ORDER_IDENTIFIER) must not be null

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.orders.AddOrderNoteActivity}: java.lang.IllegalStateException: intent.getStringExtra(FIELD_ORDER_IDENTIFIER) must not be null
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

[Fabric](https://fabric.io/automattic/android/apps/com.woocommerce.android/issues/5c40a936f8b88c296398d3ba?time=last-ninety-days)

**Comment by nbradbury** [comment]
I'm not sure how this is happening,  but here's a possibility:

* User taps an order notif for an order that hasn't been loaded yet
* Order detail appears and the order is requested
* User taps to add a note before the order request completes
* Crash because there's no order ID or number yet

**Comment by nbradbury** [comment]
Reopening since we're still seeing crash reports for this.

**Comment by nbradbury** [comment]
False alarm. The user is running a version that doesn't have the fix yet.
