### ISSUE TITLE
IllegalStateException in ReviewDetailFragment

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#733]
```
Caused by java.lang.IllegalStateException: FragmentManager is already executing transactions
       at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2179)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:837)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:797)
       at com.woocommerce.android.ui.base.TopLevelFragment.closeCurrentChildFragment(TopLevelFragment.kt:80)
       at com.woocommerce.android.ui.notifications.ReviewDetailFragment.processCommentModeration(ReviewDetailFragment.kt:213)
       at com.woocommerce.android.ui.notifications.ReviewDetailFragment.access$processCommentModeration(ReviewDetailFragment.kt:38)
       at com.woocommerce.android.ui.notifications.ReviewDetailFragment$moderateListener$1.onCheckedChanged(ReviewDetailFragment.kt:70)
       at android.widget.CompoundButton.setChecked(CompoundButton.java:181)
       at android.widget.ToggleButton.setChecked(ToggleButton.java:71)
       at android.widget.CompoundButton.onRestoreInstanceState(CompoundButton.java:622)
       at android.view.View.dispatchRestoreInstanceState(View.java:18866)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3936)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3936)
       at android.view.View.restoreHierarchyState(View.java:18844)
       at android.support.v4.app.Fragment.restoreViewState(Fragment.java:415)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1454)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2361)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1451)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
       at android.app.Activity.performStart(Activity.java:7200)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2918)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

[Fabric](https://fabric.io/automattic/android/apps/com.woocommerce.android/issues/5c4f4518f8b88c2963d476cd?time=last-ninety-days)

**Comment by nbradbury** [comment]
Looking at this section of the stack trace, it appears that restoring the fragment instance is causing the moderation button's check listener to fire, which then causes the fragment to close before it has been fully restored:

```
ReviewDetailFragment$moderateListener$1.onCheckedChanged(ReviewDetailFragment.kt:70)
       at android.widget.CompoundButton.setChecked(CompoundButton.java:181)
       at android.widget.ToggleButton.setChecked(ToggleButton.java:71)
       at android.widget.CompoundButton.onRestoreInstanceState(CompoundButton.java:622)
```
