### ISSUE TITLE
Crash: UninitializedPropertyAccessException when clicking "view orders"

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#744]
**Describe the bug**
Clicking on the "View Orders" button in the unfulfilled orders card in My Store is now crashing in the `develop` branch.

**To Reproduce**
1. Go to My Store
2. Click on View Orders
3. App crashes

**Error**
```
2019-02-04 15:48:04.551 12333-12333/com.woocommerce.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android.dev, PID: 12333
    kotlin.UninitializedPropertyAccessException: lateinit property ordersAdapter has not been initialized
        at com.woocommerce.android.ui.orders.OrderListFragment.onFilterSelected(OrderListFragment.kt:504)
        at com.woocommerce.android.ui.main.MainActivity.showOrderList(MainActivity.kt:366)
        at com.woocommerce.android.ui.dashboard.DashboardFragment$onActivityCreated$3.onViewOrdersClicked(DashboardFragment.kt:108)
        at com.woocommerce.android.ui.dashboard.DashboardUnfilledOrdersCard$initView$1.onClick(DashboardUnfilledOrdersCard.kt:35)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by nbradbury** [comment]
@AmandaRiu This fixes the crash when the orders fragment hasn't been created yet, but it still crashes when the fragment already exists.
