### ISSUE TITLE
Resources.NotFoundException during login

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#746]
From [Crashlytics](http://crashes.to/s/57ccb74f7fc):

```
Caused by android.content.res.Resources$NotFoundException: String resource ID #0x0
       at android.content.res.Resources.getText(Resources.java:348)
       at android.content.res.Resources.getString(Resources.java:441)
       at android.content.Context.getString(Context.java:578)
       at org.wordpress.android.login.LoginBaseFormFragment.startProgress(LoginBaseFormFragment.java:219)
       at org.wordpress.android.login.LoginBaseFormFragment.startProgress(LoginBaseFormFragment.java:208)
       at org.wordpress.android.login.LoginBaseFormFragment.doFinishLogin(LoginBaseFormFragment.java:254)
       at org.wordpress.android.login.Login2FaFragment.onAuthenticationChanged(Login2FaFragment.java:433)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by nbradbury** [comment]
The crash is happening in the login library, perhaps due to [this variable](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/blob/develop/WordPressLoginFlow/src/main/java/org/wordpress/android/login/Login2FaFragment.java#L85) not being assigned. Probable fix is to assign a default value to this variable.
