### ISSUE TITLE
IllegalStateException showing order filter dialog

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#765]
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
       at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
       at com.woocommerce.android.ui.orders.OrderListFragment.showFilterDialog(OrderListFragment.kt:493)
       at com.woocommerce.android.ui.orders.OrderListFragment.onOptionsItemSelected(OrderListFragment.kt:146)
       at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2476)
       at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3343)
       at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:347)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:413)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
       at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
       at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
       at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
       at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
       at android.view.View.performClick(View.java:6897)
       at android.widget.TextView.performClick(TextView.java:12693)
       at android.view.View$PerformClick.run(View.java:26101)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

http://crashes.to/s/fa2a2ec3175

**Comment by nbradbury** [comment]
We decided to close this and see if we get more instances of this. It seems odd to get this crash when the log makes it clear that the user tapped the filter icon (so we know the activity is visible).
