### ISSUE TITLE
InflateException in DashboardTopEarnersView

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#766]
Only one report of this:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}:
 android.view.InflateException: Binary XML file line #54: Binary XML file line #54:
 Error inflating class com.woocommerce.android.ui.dashboard.DashboardTopEarnersView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2750)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2811)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6316)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

http://crashes.to/s/777acc83825

**Comment by nbradbury** [comment]
Exception happens when inflating `fragment_dashboard`. Line 54 referenced in the crash log is where the top earners view appears.

**Comment by nbradbury** [comment]
[This SO answer](https://stackoverflow.com/a/23202156/1673548) looks like the likely cause. The crash is due to top earners images requiring too much memory. Need to investigate whether our method of reducing image size is actually working.

**Comment by nbradbury** [comment]
> Need to investigate whether our method of reducing image size is actually working.

It's not. We append the `?w=` query param to get the image at the exact size we need, but that doesn't always work. For example, the `w` param makes no difference here:

https://jamosova3.mystagingwebsite.com/wp-content/uploads/2017/04/fruits_1.jpg?w=140
https://jamosova3.mystagingwebsite.com/wp-content/uploads/2017/04/fruits_1.jpg?w=40

Most likely solution is to use Photon when requesting these images. In WPAndroid we have to check if the site is photon-capable before doing this, but we don't have to do this since JP sites are all capable.

**Comment by nbradbury** [comment]
Possible solution: https://stackoverflow.com/a/3739853/1673548

**Comment by nbradbury** [comment]
Note to myself: I missed this in the crash log, "Caused by android.view.InflateException: Binary XML file line #40: Binary XML file line #40: Error inflating class TextView." There's TextView on line 40 of both the top earners view and the top earners list item view.
