### ISSUE TITLE
ZenDesk Crash when clearing session storage

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#784]
From Fabric:

```
Caused by java.lang.NullPointerException: Attempt to get length of null array
       at zendesk.core.ZendeskSessionStorage.clearDirectory(ZendeskSessionStorage.java:99)
       at zendesk.core.ZendeskSessionStorage.clearDirectory(ZendeskSessionStorage.java:100)
       at zendesk.core.ZendeskSessionStorage.clear(ZendeskSessionStorage.java:83)
       at zendesk.core.ZendeskShadow.setIdentity(ZendeskShadow.java:125)
       at zendesk.core.Zendesk.setIdentity(Zendesk.java:147)
       at com.woocommerce.android.support.ZendeskHelper.refreshIdentity(ZendeskHelper.kt:306)
       at com.woocommerce.android.support.ZendeskHelper.clearIdentity(ZendeskHelper.kt:331)
       at com.woocommerce.android.support.ZendeskHelper.reset(ZendeskHelper.kt:186)
       at com.woocommerce.android.WooCommerce.onAccountChanged(WooCommerce.kt:177)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6934)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

This is a bug in the ZenDesk SDK – it seems there's a fix available by updating to version `2.1.1` or greater (https://develop.zendesk.com/hc/en-us/community/posts/360003309647-Android-Support-SDK-2-0-NullPointerException-in-ZendeskSessionStorage)

**Source:** 5c44b8bff8b88c2963f0735f-fabric

**Comment by nbradbury** [comment]
Closed via #797
