### ISSUE TITLE
Crash in Tracks

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#786]
From Fabric:

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.content.res.Resources.getDisplayAdjustments()' on a null object reference
       at android.app.ContextImpl.getDisplay(ContextImpl.java:1907)
       at android.view.WindowManagerImpl.getDefaultDisplay(WindowManagerImpl.java:149)
       at com.automattic.android.tracks.DeviceInformation.<init>(DeviceInformation.java:122)
       at com.automattic.android.tracks.TracksClient.<init>(TracksClient.java:90)
       at com.automattic.android.tracks.TracksClient.getClient(TracksClient.java:83)
       at com.woocommerce.android.analytics.AnalyticsTracker.<init>(AnalyticsTracker.kt:188)
       at com.woocommerce.android.analytics.AnalyticsTracker.<init>(AnalyticsTracker.kt:16)
       at com.woocommerce.android.analytics.AnalyticsTracker$Companion.init(AnalyticsTracker.kt:347)
       at com.woocommerce.android.WooCommerce.initAnalytics(WooCommerce.kt:138)
       at com.woocommerce.android.WooCommerce.onCreate(WooCommerce.kt:77)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
       at android.app.LoadedApk.makeApplication(LoadedApk.java:812)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3052)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1580)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6186)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Before getting to deep into this, I'd suggest updating to the most recent version of Tracks first. The stack trace for this issue doesn't match the latest version, so that might be a good place to begin.

**Source:** 5c4ef207f8b88c2963cb9a6c-fabric

**Comment by nbradbury** [comment]
Good call on updating to the most recent version of Tracks @jkmassel. Looks like this has been fixed in [this Tracks commit](https://github.com/Automattic/Automattic-Tracks-Android/commit/fa57c64f2363f87a4f41fc18cf96b18dddaa2dd2#diff-1718aa6474e6bc8491113e238aa9e95a). I'll update WCAndroid to the latest version.
