### ISSUE TITLE
com.woocommerce.android.ui.login.LoginActivity.onCreate – Could not find active fragment with index -1

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#789]
From Fabric:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.login.LoginActivity}: java.lang.IllegalStateException: Could not find active fragment with index -1
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4162)
       at android.app.ActivityThread.access$1000(ActivityThread.java:168)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5659)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
```

**First Appeared In:** 1.01

**Source:** 5c4d0c3ef8b88c2963a5ba17-fabric

**Comment by nbradbury** [comment]
Googling for this turned up a few hits suggesting that this is related to using `retainInstance = true`, which we do on the Google login fragment.

**Comment by nbradbury** [comment]
[Here's](https://android.googlesource.com/platform/frameworks/support/+/oreo-release/fragment/java/android/support/v4/app/FragmentManager.java#3025) where this is happening in the Android source code.

**Comment by murali129** [comment]
Hi there, I have ran into same issue, please suggest us if you have fixed it

**Comment by anitaa1990** [comment]
Closing this issue since this crash is not in Sentry for 90 days or more.

**Comment by joshallenit** [comment]
This can happen with a combination of [dismissAllowingStateLoss][1] after [onSaveInstanceState][1] and [retainInstanceState][2].

See [answer to "Could not find active fragment with index -1"][3]


  [1]: https://developer.android.com/reference/android/app/Fragment#onSaveInstanceState(android.os.Bundle)
  [2]: https://developer.android.com/reference/android/app/Fragment#setRetainInstance(boolean)
  [3]: https://stackoverflow.com/a/66119253/1596587
