### ISSUE TITLE
Incorrect formatting in Analytics Hub

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#7981]
### Description

When formatting values in Analytics Hub, we use currency fields from API. We have e.g. `RevenueStat#currencyCode`. Although the name suggests otherwise, we don't store currency code (EUR) in this field but instead currency symbol ($). This leads to the following exception:

```
Error finding valid currency symbol for currency code [€] in locale [nl_NL]
java.lang.IllegalArgumentException: The input currency code is not 3-letter alphabetic code.
	at android.icu.util.Currency.getInstance(Currency.java:284)
	at java.util.Currency.getInstance(Currency.java:289)
	at org.wordpress.android.fluxc.utils.WCCurrencyUtils.getLocalizedCurrencySymbolForCode(WCCurrencyUtils.kt:65)
	at org.wordpress.android.fluxc.store.WooCommerceStore.formatCurrencyForDisplay(WooCommerceStore.kt:399)
	at com.woocommerce.android.util.CurrencyFormatter.formatCurrency(CurrencyFormatter.kt:106)
	at com.woocommerce.android.util.CurrencyFormatter.formatCurrency$default(CurrencyFormatter.kt:102)
	at com.woocommerce.android.ui.analytics.AnalyticsViewModel.formatValue(AnalyticsViewModel.kt:335)
	at com.woocommerce.android.ui.analytics.AnalyticsViewModel.buildProductsDataState(AnalyticsViewModel.kt:428)
	at com.woocommerce.android.ui.analytics.AnalyticsViewModel.access$buildProductsDataState(AnalyticsViewModel.kt:65)
	at com.woocommerce.android.ui.analytics.AnalyticsViewModel$updateProducts$1.invokeSuspend(AnalyticsViewModel.kt:241)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7929)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Expected behavior

Values in Analytics Hub should be correctly formatted.

### Ideas

Maybe we shouldn't even request `currencyCode` for `RevenueStat` and others but only use the store currency?

**Comment by malinajirka** [comment]
Automated test and comment: I could not reproduce this on 2026-06-15. I checked the current currency formatting path and it now catches IllegalArgumentException for invalid currency codes, returning the raw value instead of crashing. I also temporarily set the staging store currency option to the symbol € to simulate the bad analytics currencyCode value from the report, relaunched WooCommerce Android dev build 24.9-rc-3 on Medium_Phone_API_35 / emulator-5558, and did not observe the reported crash in logcat. Closing this issue by automation since our reproduction attempt failed. Please reopen if this is still reproducible with current builds and fresh steps/data.
