### ISSUE TITLE
java.lang.IndexOutOfBoundsException in notif list

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#816]
A crash from Fabric:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 6(offset:9).state:7 android.support.v7.widget.RecyclerView{[redacted] app:id/notifsList}, adapter:com.woocommerce.android.ui.notifications.NotifsListAdapter@13d7526, layout:android.support.v7.widget.LinearLayoutManager@240a567, context:com.woocommerce.android.ui.main.MainActivity@3f124ad
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5923)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
       at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1888)
       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5044)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
       at android.view.Choreographer.doCallbacks(Choreographer.java:696)
       at android.view.Choreographer.doFrame(Choreographer.java:628)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:870)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

```
**Source:** fabric-5c67ee5df8b88c296309c65d
**First Appeared In:** `1.2-rc-2`

**Comment by nbradbury** [comment]
Note that there are three instances of this crash, but they're all for the same user. It appears that the crash occurs while performing a fling of the notification list.

**Comment by nbradbury** [comment]
I had this crash happen to me today. It's not caused by flinging but instead by quickly trashing or spamming multiple review notifications.

I _think_ the problem may be due to us storing a single `pendingRemovalNotification`.

**Comment by nbradbury** [comment]
Update: I'm seeing a lot of instances of this in the user logs for this crash:
```
D/CrashlyticsCore w/WooCommerce-NOTIFICATIONS: Failed to get item type at recycler position -1
--
