### ISSUE TITLE
Error inflating class com.woocommerce.android.ui.main.MainNavigationView

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#822]
From Fabric:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: android.view.InflateException: Binary XML file line #41: Error inflating class com.woocommerce.android.ui.main.MainNavigationView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2193)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
       at android.app.ActivityThread.access$800(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5019)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
**Similar to:** https://github.com/woocommerce/woocommerce-android/issues/766
**Source:** 5c6c7989f8b88c29636ea930-fabric

**Comment by nbradbury** [comment]
Looks like a missing resource is the culprit:
```
Caused by android.content.res.Resources$NotFoundException:
File res/drawable-v21/design_bottom_navigation_item_background.xml
from drawable resource ID #0x7f08007e
       at android.content.res.Resources.loadDrawable(Resources.java:2096)
       at android.content.res.Resources.getDrawable(Resources.java:700)
       at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:74)
       at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:433)
       at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:67)
       at android.view.View.setBackgroundResource(View.java:15303)
       at android.support.design.internal.BottomNavigationItemView.<init>(BottomNavigationItemView.java:88)
       at android.support.design.internal.BottomNavigationItemView.<init>(BottomNavigationItemView.java:72)
       at android.support.design.internal.BottomNavigationItemView.<init>(BottomNavigationItemView.java:68)
       at android.support.design.internal.BottomNavigationMenuView.getNewItem(BottomNavigationMenuView.java:322)
       at android.support.design.internal.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:275)
       at android.support.design.internal.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:62)
       at android.support.design.widget.BottomNavigationView.inflateMenu(BottomNavigationView.java:236)
       at android.support.design.widget.BottomNavigationView.<init>(BottomNavigationView.java:165)
       at com.woocommerce.android.ui.main.MainNavigationView.<init>(MainNavigationView.kt:27)
       at com.woocommerce.android.ui.main.MainNavigationView.<init>(MainNavigationView.kt:26)
       at com.woocommerce.android.ui.main.MainNavigationView.<init>(MainNavigationView.kt)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at com.woocommerce.android.ui.main.MainActivity.onCreate(MainActivity.kt:89)
       at android.app.Activity.performCreate(Activity.java:5231)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
       at android.app.ActivityThread.access$800(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5019)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by nbradbury** [comment]
Strange, the missing resource is part of the material components - see [here](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomnavigation/BottomNavigationItemView.java#L87). I'm not sure how this could happen, but I'll investigate.

**Comment by nbradbury** [comment]
I'm going to close this without a solution. The problem happened to one user and seems specific to their device. There are no reports of this since Feb 20.
