### ISSUE TITLE
Zendesk: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#823]
From Fabric:

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver zendesk.support.DeepLinkingBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2586)
       at android.app.ActivityThread.access$1700(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Source:** 5c64bb2ff8b88c2963be6ddf-fabric

**Comment by AmandaRiu** [comment]
Opened a ticket with Zendesk: https://support.zendesk.com/hc/en-us/requests/4455989

**Comment by AmandaRiu** [comment]
I was digging further into this issue while trying to break it down for Zendesk and realized we only see this crash from a "batmobile" device running Android 5.0.2, and mostly only happens exactly once per release. "Batmobile" isn't a real manufacturer and the device name of "Defy Mini" appears to have been a Motorola device that only went up to Android 2. The overall consensus here and here is that this is a fake device, likely a bot scanning our app. It's been known to spam crashlytics with crashes usually right after a new release..and then the crashes magically disappear. You can see this trend in our own logs. Closing this ticket as a non-issue.
