### ISSUE TITLE
IndexOutOfBoundsException after trashing notification

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#843]
I added a number of reviews to my test site, then later trashed them one-by-one in app. In the process, the app crashed with this:

```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 17(offset:20).state:18 android.support.v7.widget.RecyclerView{ff0b27b VFED..... .F....ID 0,0-1440,2236 #7f0a0155 app:id/notifsList}, adapter:com.woocommerce.android.ui.notifications.NotifsListAdapter@5ffa898, layout:android.support.v7.widget.LinearLayoutManager@c948f1, context:com.woocommerce.android.ui.main.MainActivity@927d0b2
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5923)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
        at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1888)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5044)
```

This _may_ be a dup of #816

**Comment by nbradbury** [comment]
Looking at the logs attached to #816, it appears the user was spamming reviews, in which case this **is** a dup so closing it.
