### ISSUE TITLE
Crash in reportSizeConfigurations: ActivityRecord not found for: Token

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#855]
From Fabric:

```
Fatal Exception: java.lang.IllegalArgumentException: reportSizeConfigurations: ActivityRecord not found for: Token{9420726 null}
       at android.os.Parcel.createException(Parcel.java:1954)
       at android.os.Parcel.readException(Parcel.java:1918)
       at android.os.Parcel.readException(Parcel.java:1868)
       at android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations(IActivityManager.java:8679)
       at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3217)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3176)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4920)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4829)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
       at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4879)
       at android.app.ActivityThread.access$3400(ActivityThread.java:207)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

A quick StackOverflow search led me to this, which seems like a likely culprit?

https://stackoverflow.com/questions/46309428/android-activitythread-reportsizeconfigurations-causes-app-to-freeze-with-black

**Source:** 5c73f278f8b88c296313705a-fabric
**First Appeared In:** `1.0.1`

**Comment by AmandaRiu** [comment]
So far this has only happened to a single user, if this was due to the app hanging I think we'd see a lot more of these crashes. I'll keep it open for another couple weeks to see if it happens to any other users before closing.

**Comment by AmandaRiu** [comment]
Crash has only happened a single time in the last 90 days. Closing as a non-issue.
