### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#916]
From Fabric:

```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:807)
       at com.woocommerce.android.ui.base.TopLevelFragment.popToState(TopLevelFragment.kt:76)
       at com.woocommerce.android.ui.base.TopLevelFragmentView$DefaultImpls.openOrderFulfillment(TopLevelFragmentView.kt:103)
       at com.woocommerce.android.ui.base.TopLevelFragment.openOrderFulfillment(TopLevelFragment.kt:18)
       at com.woocommerce.android.ui.orders.OrderDetailFragment.openOrderFulfillment(OrderDetailFragment.kt:199)
       at com.woocommerce.android.ui.orders.OrderDetailProductListView$initView$$inlined$let$lambda$1.onClick(OrderDetailProductListView.kt:54)
       at android.view.View.performClick(View.java:6891)
       at android.widget.TextView.performClick(TextView.java:12651)
       at android.view.View$PerformClick.run(View.java:26083)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Seems similar to:** https://github.com/woocommerce/woocommerce-android/issues/644
**Users affected:** 1
**Source:** 5c895ddaf8b88c2963fd646d-fabric

**Comment by anitaa1990** [comment]
@AmandaRiu this crash is happening in an older version of the app (1.0.1). I believe there have been some significant changes to the `TopLevelFragment` since the 1.0.1 release. The problem happened to one user and there have not been any reports of this since March 12.

So closing this issue.
