### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.Object org.wordpress.android.fluxc.network.rest.wpcom.jetpacktunnel.JetpackTunnelResponse.getData()' on a null object reference

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#917]
From Fabric:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object org.wordpress.android.fluxc.network.rest.wpcom.jetpacktunnel.JetpackTunnelResponse.getData()' on a null object reference
       at org.wordpress.android.fluxc.network.rest.wpcom.jetpacktunnel.JetpackTunnelGsonRequest$buildGetRequest$wrappedListener$1.onResponse(JetpackTunnelGsonRequest.kt:118)
       at org.wordpress.android.fluxc.network.rest.wpcom.jetpacktunnel.JetpackTunnelGsonRequest$buildGetRequest$wrappedListener$1.onResponse(JetpackTunnelGsonRequest.kt:89)
       at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:52)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
       at android.os.Handler.handleCallback(Handler.java:891)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

Good chance this is either a FluxC bug, or a callback object is missing by the time the response is complete?

**First Appeared In:** `1.0.1`
**Users Affected:** 5 (between all related issues)
**Source:** 5c8907c4f8b88c2963f39324-fabric

**Comment by jkmassel** [comment]
An additional crash seems very similar: `5c8904a9f8b88c2963f335fa-fabric`

**Comment by jkmassel** [comment]
An additional crash that seems very similar: `5c890444f8b88c2963f32a23-fabric`

**Comment by anitaa1990** [comment]
@AmandaRiu, @nbradbury 
I was looking into this issue today. There are 4 users affected. 

1 user got this error:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object org.wordpress.android.fluxc.network.rest.wpcom.jetpacktunnel.JetpackTunnelResponse.getData()' on a null object reference
at org.wordpress.android.fluxc.network.rest.wpcom.jetpacktunnel.JetpackTunnelGsonRequest$buildGetRequest$wrappedListener$1.onResponse(JetpackTunnelGsonRequest.kt:118)
at org.wordpress.android.fluxc.network.rest.wpcom.jetpacktunnel.JetpackTunnelGsonRequest$buildGetRequest$wrappedListener$1.onResponse(JetpackTunnelGsonRequest.kt:89)
at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:52)
```

1 user got this error:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.gson.JsonElement org.wordpress.android.fluxc.network.rest.wpcom.wc.orderstats.OrderStatsApiResponse.getFields()' on a null object reference
at org.wordpress.android.fluxc.network.rest.wpcom.wc.orderstats.OrderStatsRestClient$fetchStats$request$1.onResponse(OrderStatsRestClient.kt:78)
at org.wordpress.android.fluxc.network.rest.wpcom.wc.orderstats.OrderStatsRestClient$fetchStats$request$1.onResponse(OrderStatsRestClient.kt:29)
at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:52)
```

2 users got this error when trying to call the `registerDeviceForPushNotifications` method:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.network.rest.wpcom.notifications.RegisterDeviceRestResponse.getId()' on a null object reference
at org.wordpress.android.fluxc.network.rest.wpcom.notifications.NotificationRestClient$registerDeviceForPushNotifications$request$1.onResponse(NotificationRestClient.kt:76)
at org.wordpress.android.fluxc.network.rest.wpcom.notifications.NotificationRestClient$registerDeviceForPushNotifications$request$1.onResponse(NotificationRestClient.kt:37)
at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:52)
```


I'm not sure all the points gathered here are relevant but would like to note it down here:
* All exceptions occurred in app version 1.0.1
* I SSP'ed  into 3 accounts and was able to successfully view the dashboard. 
* This exception occurs because the response from the server is `null`.
* I _think_ it's possible that a request reached the server but the reply did not to get back to the device because of flaky network connections. I tried simulating bad network connection from my test site and while there were some api errors, none of them was null.

I thought of perhaps making modifications to FluxC methods to expect null responses as well. Would this be a good approach to take? This would make the app more resilient to API issues as well as flaky network issues.

**Comment by AmandaRiu** [comment]
@anitaa1990 I like the idea of just catching that null response and letting the client handle it by showing an error message to the user. We do the same for all other areas of the app. This will help by adding additional logging which is nice, and will pave the way for when we have specific views that walk the user through troubleshooting steps. Once that logic is added, I'd close this ticket. The complaints haven't happened in a very long time that are specific to this issue.
