### ISSUE TITLE
Multiple Dead System Exception Crashes

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#920]
From Fabric:

```
Fatal Exception: java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.ActivityThread.handleSleeping(ActivityThread.java:4522)
       at android.app.ActivityThread.access$2400(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1884)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

```
Fatal Exception: java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:408)
       at android.app.NotificationManager.notify(NotificationManager.java:370)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:210)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:194)
       at com.woocommerce.android.push.NotificationHandler.showNotificationForBuilder(NotificationHandler.kt:532)
       at com.woocommerce.android.push.NotificationHandler.showWPComNotificationForBuilder(NotificationHandler.kt:512)
       at com.woocommerce.android.push.NotificationHandler.showSingleNotificationForBuilder(NotificationHandler.kt:428)
       at com.woocommerce.android.push.NotificationHandler.buildAndShowNotificationFromNoteData(NotificationHandler.kt:265)
       at com.woocommerce.android.push.FCMMessageService.onMessageReceived(FCMMessageService.kt:27)
       at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:402)
       at com.google.firebase.iid.zzg.run(Unknown Source:26)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
       at java.lang.Thread.run(Thread.java:764)
```

It looks like in some cases, the app is trying to do some work while the system is shutting down. In one case, it appears that a callback is running when the system is shutting down (or going to sleep...?) and it's crashing the app.

**Users Affected:** ~5 across several crash reports
**First Seen In:** `1.0.1`
**Sources:**

- [ ] `5c81697ff8b88c29634300a5-fabric`
- [ ] `5c88c55af8b88c2963ec6ed7-fabric`
- [ ] `5c63d165f8b88c2963a658b9-fabric`

**Comment by nbradbury** [comment]
Possible fix: https://stackoverflow.com/a/46031036/1673548

**Comment by nbradbury** [comment]
Notes for myself: `FCMMessageService` starts `NotificationsProcessingService` when it wants to show a notification.  If `FCMMessageService` is killed before `NotificationsProcessingService` has a chance to start, it _could_ lead to this exception.

 I'm wondering if this is due to passing the context of `FCMMessageService` [here](https://github.com/woocommerce/woocommerce-android/blob/031b45fcc1bc11a020334a1e896eb059dc78dbc1/WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMMessageService.kt#L27), and if so whether it could be resolved by passing the application context instead.

**Comment by nbradbury** [comment]
Update: The previous comment is unlikely to be the answer. I believe Jack Wharton is right [here](https://github.com/square/picasso/issues/1903#issuecomment-403518470) when he recommends ignoring it. Since the system is restarting there's really nothing we can do but catch the exception and ignore it.
