### ISSUE TITLE
Attempt to invoke virtual method 'long org.wordpress.android.fluxc.model.SiteModel.getSiteId()' on a null object

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#934]
From Fabric:

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'long org.wordpress.android.fluxc.model.SiteModel.getSiteId()' on a null object reference
       at com.woocommerce.android.ui.sitepicker.SitePickerActivity.showStoreList(SitePickerActivity.kt:196)
       at com.woocommerce.android.ui.sitepicker.SitePickerActivity.onCreate(SitePickerActivity.kt:106)
       at android.app.Activity.performCreate(Activity.java:5975)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.access$800(ActivityThread.java:147)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5264)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
```

**First Seen In:** `1.3.2`
**Users Affected:** 1
**Source:** `5c95dacaf8b88c29633d21bb-fabric`

**Comment by nbradbury** [comment]
This is one of those "shouldn't be possible" bugs :) The crash is happening [here](https://github.com/woocommerce/woocommerce-android/blob/amanda/1.3-release.fix/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt#L196) where we access `wcSites[0]`, and we know that `wcSites` isn't empty.

**Comment by jkmassel** [comment]
We're checking `isEmpty`, but is it possible that a site exists at array index `1` or something? Or does a `List` disallow sparse ordering?

Sort of a long shot, but the only thing I could think of 🙃

**Comment by nbradbury** [comment]
The list of sites is pulled from SQlite via FluxC so there _shouldn't_ be any empty entries. I'm putting this one on the backburner for now, but it is a mystery.

**Comment by anitaa1990** [comment]
Closing this issue since there have been no new crashes since June 2019
