### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Results have already been set

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#948]
From Fabric, this incredibly unhelpful stack trace:

```
Fatal Exception: java.lang.IllegalStateException: Results have already been set
       at Jq.a(Jq.java:17)
       at com.google.android.gms.common.api.internal.BasePendingResult.a(BasePendingResult.java:95)
       at GH.b(GH.java:19)
       at Ie.a(Ie.java:15)
       at Ie.a(Ie.java:9)
       at GM.c(GM.java:148)
       at GM.b(GM.java:141)
       at GM.c(GM.java:107)
       at GM.a(GM.java:38)
       at GM.a(GM.java:28)
       at IO.a(IO.java:25)
       at IJ.a(IJ.java:12)
       at IK.handleMessage(IK.java:58)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**First Appeared In:** `1.5-rc-1`
**Users Affected:** `1`
**Source:** `5c9caadef8b88c2963191944-fabric`

**Comment by anitaa1990** [comment]
Googling this and found that this is an issue with gms and there is an issue tracker already started [here](https://issuetracker.google.com/issues/70416429). There hasn't been any update from Google's end on this.

This [SO answer](https://stackoverflow.com/a/49165418/9862062) provides a hack to catch this particular exception when initialising the app, and handling it.

**Comment by anitaa1990** [comment]
Issue on hold for now since it happened for one user over a month ago. Will revisit [PR](https://github.com/woocommerce/woocommerce-android/pull/1021) if issue persists: see comments [here](https://github.com/woocommerce/woocommerce-android/pull/1021#issuecomment-486161419).

**Comment by anitaa1990** [comment]
No more instances of this have been reported and this only happened to a single user over a month ago. Closing.
