### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: empty_view must not be null

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#956]
From Fabric:

```
Fatal Exception: java.lang.IllegalStateException: empty_view must not be null
       at com.woocommerce.android.ui.orders.OrderListFragment.shouldShowFilterMenuItem(OrderListFragment.java:164)
       at com.woocommerce.android.ui.orders.OrderListFragment.refreshOptionsMenu(OrderListFragment.java:134)
       at com.woocommerce.android.ui.orders.OrderListFragment.onPrepareOptionsMenu(OrderListFragment.java:118)
       at android.support.v4.app.Fragment.performPrepareOptionsMenu(Fragment.java:2575)
       at android.support.v4.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManagerImpl.java:3353)
       at android.support.v4.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:343)
       at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:548)
       at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
       at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:2576)
       at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
       at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:522)
       at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
       at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:887)
       at android.view.Choreographer.doCallbacks(Choreographer.java:699)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6349)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

**First Seen In:** `1.4`
**Users Affected:** `1`
**Source:** `5c9d5f34f8b88c296339865b-fabric`

**Comment by AmandaRiu** [comment]
Submitted a ticket to Zendesk: https://support.zendesk.com/hc/en-us/requests/4455989
