### ISSUE TITLE
intent.getStringExtra(FIELD_ORDER_IDENTIFIER) must not be null

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#957]
From Fabric:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.orders.AddOrderNoteActivity}: java.lang.IllegalStateException: intent.getStringExtra(FIELD_ORDER_IDENTIFIER) must not be null
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**First Seen In:** `1.4`
**Users Affected:** `2`
**Source:** `5c9d5467f8b88c2963382878-fabric`

**Comment by nbradbury** [comment]
Looks like this wasn't fixed by #721 after all 😞
