### ISSUE TITLE
Crash in com.woocommerce.android.ui.base.TopLevelFragment.popToState

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#978]
From Fabric:

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: java.lang.IllegalStateException: Fragment has not been attached yet.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**First Seen In:** `1.6-rc-1`
**Users Affected:** `28`
**Crashes**: `53`
**Source:** `5cabe10ef8b88c296319948f-fabric`

**Comment by jkmassel** [comment]
@AmandaRiu – just wanted to check on this – I see it's moved to "done" – can we close it? 

We're up to 533 crashes / 159 users in `1.6-rc-1`, so if it's resolved, I'd love to ship a hot fix! 😊

**Comment by AmandaRiu** [comment]
Ah, sorry @jkmassel I thought you knew - this was all fixed in the associated PR: https://github.com/woocommerce/woocommerce-android/pull/983
