### ISSUE TITLE
Attempt to invoke 'charting.data.BarData.clearValues()' on a null object reference

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#979]
From Fabric:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.mikephil.charting.data.BarData.clearValues()' on a null object reference
       at com.woocommerce.android.ui.dashboard.DashboardStatsView.clearChartData(DashboardStatsView.java:333)
       at com.woocommerce.android.ui.dashboard.DashboardFragment.refreshDashboard(DashboardFragment.java:223)
       at com.woocommerce.android.ui.dashboard.DashboardFragment$onCreateFragmentView$$inlined$with$lambda$1.onRefresh(DashboardFragment.java:73)
       at android.support.v4.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:195)
       at android.support.v4.widget.CircleImageView.onAnimationEnd(CircleImageView.java:107)
       at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:6912)
       at android.view.View.draw(View.java:20272)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1963)
       at android.view.View.draw(View.java:20369)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.updateDisplayListIfDirty(View.java:19232)
       at android.view.View.draw(View.java:20094)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
       at android.view.View.draw(View.java:20369)
       at com.android.internal.policy.DecorView.draw(DecorView.java:781)
       at android.view.View.updateDisplayListIfDirty(View.java:19241)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3515)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3312)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2681)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1633)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7786)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
       at android.view.Choreographer.doCallbacks(Choreographer.java:816)
       at android.view.Choreographer.doFrame(Choreographer.java:751)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**First Seen In:** `1.6-rc-1`
**Users Affected:** `4`
**Number of Crashes:** `7`
**Source:** `5cac55c1f8b88c29632502a7-fabric`

**Comment by nbradbury** [comment]
Closed via #985
