### ISSUE TITLE
Unable to start activity `MainActivity`: widget.AppCompatBackgroundHelper.onSetBackgroundDrawable

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#980]
From Fabric:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.AppCompatBackgroundHelper.onSetBackgroundDrawable$130e17e7()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Users Affected:** `2`
**Crash Count:** `3`
**Source:** `5ca66600f8b88c2963736d47-fabric`

**Comment by nbradbury** [comment]
Note that this appears to be just one user experiencing the problem, and they have a rooted device.

**Comment by jkmassel** [comment]
Looks like you're right – odd that Fabric says it was two users 🤔

**Comment by anitaa1990** [comment]
Strange! I've been trying to reproduce this issue for a couple of days now without any luck! The issue seems to happen when trying to set toolbar [here](https://github.com/woocommerce/woocommerce-android/blob/develop/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt#L94)

The device is an emulator (Google Pixel running on 8.1, to be specific) and it could be related to their emulator configuration.

Will investigate further on whether emulators can cause this to happen

**Comment by nbradbury** [comment]
@anitaa1990 I'd be fine to just close this issue. It happened to one user on a rooted device (emulator), so I don't think it's worth our time to keep looking into it unless it reoccurs. Agreed?

**Comment by anitaa1990** [comment]
Yup, I'm good with that! Spent a couple of hours on this and couldn't find anything helpful
